### ISSUE TITLE
JOnAS integration

### ISSUE THREAD

**Issue by typekpb** [p6spy/p6spy#179]
While working on integration tests on JOnAS, I've found interesting stuff.

So JOnAS seem to be different and tries to support p6spy. The problem is however, that once I configured it, it just expected specific class to be available on classpath, namely:  `org.objectweb.util.monolog.wrapper.p6spy.P6SpyLogger`

I've found out that there is an implementation available:

    <dependency>
     <groupId>org.ow2.monolog</groupId>
     <artifactId>monolog-wrapper-p6spy</artifactId>
     <version>2.2.1-RC1</version>
    </dependency>

However this one is compatible with P6Spy 1.3 only.

So I decided to make JOnAS happy, providing initial implementation directly in P6Spy.

Some details on the initial implementation can be found in javadocs of: 3f2c2883bd78ddb03d2a12d7d7231a5c163b9e1a

As a quick hack it worked. As it just inherits from the FileLogger => we get all stuff logged to file and my integration test is happy.

Still, there are open points:
 - we should probably handle situation like this one in a specific jar file
 - similar to slf4j concept, we could produce multiple maven modules (each one holding class: `org.objectweb.util.monolog.wrapper.p6spy.P6SpyLogger`) and  depending on what end user needs to achieve, he'd add the right one to classpath. Basically these could just have different superclass: `FileLogger`, `WhateverLogger`,...

I think what I've done is messy. It's even preventing different implementation (other than `FileLogger` one, as loading order of the same called class from the various jars is random), still, wanted to start with something basic we can prove to be working.

The question is however, how many people really use p6psy on JOnAS, if it makes sense to go for something more sophisticated like this at all. 

Maybe we should we just provide this implementation in a separate jar (maven module) and let people implement themselves if they really need it. And include this jar in our integration tests then. Still, I'd like to keep the same versioning as the p6spy has, as compatibility might come to play here.

Btw, implementation seems to work, see: https://travis-ci.org/p6spy/p6spy-it/builds/15069162 (jonas-5.x job)

Ideas?/Comments?

**Comment by quintonm** [comment]
JOnAS team doesn't seem to be interested in fixing this...  closing issue.
