### ISSUE TITLE
p6spy no longer works with WebSphere

### ISSUE THREAD

**Issue by quintonm** [p6spy/p6spy#186]
As reported in [this forum post](https://groups.google.com/forum/#!topic/p6spy-developers/B_58WM7fslU), p6spy is not working with more recent versions of websphere.   P6Spy 1.3 was documented to work with WebSphere 4 but no longer seems to work with WebSphere 7+ (possible stopped working before 7).  

The problem reported in the server's log file is 'DSRA8101E: DataSource class cannot be used as one-phase: ClassCastException: com.ibm.ws.rsadapter.jdbc.WSJdbcDataSource cannot be cast to javax.sql.ConnectionPoolDataSourcejava.sql.SQLException: DSRA8101E: DataSource class cannot be used as one-phase: ClassCastException: com.ibm.ws.rsadapter.jdbc.WSJdbcDataSource cannot be cast to javax.sql.ConnectionPoolDataSource'.

This problem is actually occurring inside of P6ConnectionPoolDataSource.getPooledConnection().  After the real data source is returned from the JDNI lookup, it is cast to ConnectionPoolDataSource.  This fails because the object returned is an instance of WSJdbcDataSource which does not implement the ConnectionPoolDataSource interface.  It appears that this class is a proxy for the actual data source.  Executing rds.isWrapperFor(ConnectionPoolDataSource.class) returns true.

According to [this post on developer works](https://www.ibm.com/developerworks/community/forums/html/topic?id=77777777-0000-0000-0000-000013779511&ps=50), it has not worked with 5.X.  The only method that anyone found to make it work again is to subclass the read data source class and override the various methods to get a connection (see the forum post for details).  It seems that there was a change in the data source adapter class in WebSphere somewhere between version 4.0 and 5.1.  The link in the forum post to this information no longer works though.  I am guessing that the object returned from JNDI used to implement ConnectionPoolDataSource.

Note: This could be fixed by #185.

Another _possible_ solution would be to provide subclasses for the vendor provided data sources for the more popular database vendors.  Although this would certainly work, it might be a bit difficult to maintain.

**Comment by typekpb** [comment]
some fresh air here, see: https://groups.google.com/forum/#!msg/p6spy-developers/B_58WM7fslU/KURX3TooLyQJ;context-place=forum/p6spy-developers (12/09/2016 msg)

**Comment by typekpb** [comment]
unfortunately, we have no solution for this one
