### ISSUE TITLE
Allow for configuration of real data source through p6spy configuration

### ISSUE THREAD

**Issue by quintonm** [p6spy/p6spy#229]
As of P6Spy 2.0.2, the only way to use P6Spy with a JNDI DataSource (configured with a DataSource implementation as opposed to a Driver) is to create a second data source.  The P6Spy data source is configured with the JNDI name of the real data source to form a proxy.  

Although this works for some use cases, it fails when the application server needs to be configured with a DataSource implementation that implements something other than the javax.sql.DataSource interface (ConnectionPoolingDataSource or XADataSource for example).  The problem here is that when the DataSource is returned from JNDI, it will often be a proxy which implements only the DataSource interface.  

One solution to this issue is to allow P6DataSource to create the underlying data source instead of obtaining it through a JNDI lookup.  This would require that the user supply the configuration settings needed for the data source through spy.properties (or equiv).  Since the underlying data source is created by P6Spy, there would be no need to create a second data source at all.

Note: It is possible that more specific subclasses of P6DataSource will need to be created to match the interfaces implemented by the real data source implementations.  For example, if the underlying data source does not implement XADataSource then it could present a problem if the P6Spy proxy data source did.  However, testing with ap servers will be needed to determine if this is the case,

**Comment by typekpb** [comment]
no volunteers for implementation for 4 years => closing
