### ISSUE TITLE
DB2 not working after upgrade from 1.3

### ISSUE THREAD

**Issue by dcompiled** [p6spy/p6spy#249]
I have been using p6spy with DB2 on version 1.3.  Works fine except it has a major limitation of logging all the resultsets which is quite unnecessary and wasteful.  I tried upgrading but I cannot get any logging to work.  I am using Hibernate and DB2.  My old spy.properties included realdriver=com.ibm.db2.jcc.DB2Driver.  The new spy.properties does not seem to mention realdriver.  I tried replacing realdriver with driverlist but again no results were logged.  Is there something I am missing here?

My hibernate config remains unchanged with this inculded:
        <property name="connection.driver_class">com.p6spy.engine.spy.P6SpyDriver</property>

**Comment by davutg** [comment]
I'm trying to use it with jetty.
Getting following error.
Cannot create JDBC driver of class 'com.ibm.db2.jcc.DB2Driver' for connect URL 'jdbc:p6spy:db2:

Even I change this from hibernate config  it gives same error. with p6spy or without it. spy.properties in classpath and seems like

realdriver=com.ibm.db2.jcc.DB2Driver
url=jdbc:p6spy:db2://...

What can else I need to check or do ? It's v2.1.4 , maven edition.

**Comment by quintonm** [comment]
You might need to change realdriver to driverlist.  This setting was renamed in P6Sy 2.0.  If you are using the same spy.properties file that you were using with 1.3, you should replace it with a 2.X compatible version. See [the docs](http://p6spy.github.io/p6spy/2.0/configandusage.html) for details.

`driverlist=com.ibm.db2.jcc.DB2Driver`

If that dos not solve your problem, then please post the following information into a new issue:
1) Version of jetty & applicable configuration files (the data source configuration is all that maters)
2) Full stack trace for exception
3) spy.properties
