### ISSUE TITLE
Ability to distinguish different datasources

### ISSUE THREAD

**Issue by ssaarinen** [p6spy/p6spy#253]
We have situation where we have deployed multiple data sources that p6spy is being used with in single application server. Currently there is no way to configure these separatelly or filter logs based on from what datasource the logs came from. It would be nice to get this info somehow available. 

When I thought about it, it could be solved by adding possibility to log the jdbcUrl or realDatasource name with rest of the info. Or maybe add a way to map jdbcUrl in the configs to something shorter to be appended in the logs.

**Comment by typekpb** [comment]
no volunteers for the implementation for 4 years => closing
