### ISSUE TITLE
warning fetching 2.1.2 from maven repo

### ISSUE THREAD

**Issue by abstratt** [p6spy/p6spy#276]
Got this while fetching p6spy as a dependency in my pom.xml file. Note that that path 

```
[WARNING] The POM for p6spy:p6spy:jar:2.1.2 is invalid, transitive dependencies (if any) will not be available: 1 problem was encountered while building the effective model for p6spy:p6spy:2.1.2
[ERROR] 'dependencies.dependency.systemPath' for p6spy:p6spy-signedjar-test:jar must specify an absolute path but is C:\dev\p6spy\p6spy/src/test/resources/p6spy-signedjar-test-1.0.0.jar @ 
```

Not sure about whether this has actual bad effects, I figure this dependency is not needed in normal scenarios, but wonder if it doesn't stop other dependencies from being fetched by Maven.

**Comment by quintonm** [comment]
It is a harmless warning message.  The dependency it is referring to is only used by tests.

**Comment by karolmie1** [comment]
Also fixed in scope of https://github.com/p6spy/p6spy/issues/300
