### ISSUE TITLE
P6SPY can't work properly with osgi

### ISSUE THREAD

**Issue by hellorachid** [p6spy/p6spy#279]
i used p6spy with osgi ( KARAF) but it not work

**Comment by quintonm** [comment]
Any idea why it doesn't work with OSGI?

**Comment by hellorachid** [comment]
i think the properties file dont load correctly i put the file in karaf global variables "/etc" but i doesn't work 
or may be because of the driver because i change the driver in oersistance unit but not in DataSource
note : when i try to change DataSource to P6SPY DataSource driver it say that the url doesn't exist 
if you wanna a dump i can show it to you

**Comment by quintonm** [comment]
If the JDBC url does not work after modifying the url, it means that you are having classpath problems.  Your application must import the com.p6spy.engine.spy package to be able to load P6SpyDataSource or P6SpyDriver.  The P6Spy module will need to have access to the packages for the real JDBC driver and spy,properties.

Information on other ways to load spy.properties (other than classpath) as well as alternate means of supplying configuration are documented at http://p6spy.github.io/p6spy/2.0/configandusage.html.
