### ISSUE TITLE
p6spy doesn't work with the latest Microsoft JDBC driver 

### ISSUE THREAD

**Issue by myohannes** [p6spy/p6spy#280]
New Driver Site: http://www.microsoft.com/en-us/download/details.aspx?id=11774

'

**Comment by quintonm** [comment]
Do you have an error message or stack trace?

Are you using the 4.0 or 4.1 driver?

**Comment by quintonm** [comment]
Also, what version of p6spy are you using?

**Comment by quintonm** [comment]
I have been able to run the p6spy unit tests against SQL server 2008 using the latest driver.
