### ISSUE TITLE
P6spy with JBoss when I start the server we get below error

### ISSUE THREAD

**Issue by JaikarAuvit** [p6spy/p6spy#289]
07:18:03,012 INFO  [org.jboss.as.naming] (MSC service thread 1-8) JBAS011802: Starting Naming Service
07:18:03,131 ERROR [stderr] (ServerService Thread Pool -- 27) Cannot instantiate com.p6spy.engine.logging.appender.FileLogger, even on second attempt.
07:18:03,136 ERROR [stderr] (ServerService Thread Pool -- 27) java.lang.ClassNotFoundException: com.p6spy.engine.logging.appender.FileLogger
07:18:03,137 ERROR [stderr] (ServerService Thread Pool -- 27)   at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
07:18:03,138 ERROR [stderr] (ServerService Thread Pool -- 27)   at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
07:18:03,139 ERROR [stderr] (ServerService Thread Pool -- 27)   at java.security.AccessController.doPrivileged(Native Method)
07:18:03,140 ERROR [stderr] (ServerService Thread Pool -- 27)   at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
07:18:03,141 ERROR [stderr] (ServerService Thread Pool -- 27)   at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
07:18:03,142 ERROR [stderr] (ServerService Thread Pool -- 27)   at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
07:18:03,142 ERROR [stderr] (ServerService Thread Pool -- 27)   at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
07:18:03,143 ERROR [stderr] (ServerService Thread Pool -- 27)   at com.p6spy.engine.spy.option.P6OptionsRepository.parse(P6OptionsRepository.java:116)
07:18:03,145 ERROR [stderr] (ServerService Thread Pool -- 27)   at com.p6spy.engine.spy.option.P6OptionsRepository.setOrUnSet(P6OptionsRepository.java:76)
07:18:03,146 ERROR [stderr] (ServerService Thread Pool -- 27)   at com.p6spy.engine.spy.option.P6OptionsRepository.set(P6OptionsRepository.java:61)
07:18:03,147 ERROR [stderr] (ServerService Thread Pool -- 27)   at com.p6spy.engine.spy.P6SpyOptions.setAppender(P6SpyOptions.java:350)
07:18:03,148 ERROR [stderr] (ServerService Thread Pool -- 27)   at com.p6spy.engine.spy.P6SpyOptions.load(P6SpyOptions.java:97)
07:18:03,154 ERROR [stderr] (ServerService Thread Pool -- 27)   at com.p6spy.engine.spy.P6ModuleManager.loadOptions(P6ModuleManager.java:192)
07:18:03,155 ERROR [stderr] (ServerService Thread Pool -- 27)   at com.p6spy.engine.spy.P6ModuleManager.registerModule(P6ModuleManager.java:164)
07:18:03,156 ERROR [stderr] (ServerService Thread Pool -- 27)   at com.p6spy.engine.spy.P6ModuleManager.<init>(P6ModuleManager.java:129)
07:18:03,157 ERROR [stderr] (ServerService Thread Pool -- 27)   at com.p6spy.engine.spy.P6ModuleManager.initMe(P6ModuleManager.java:73)
07:18:03,158 ERROR [stderr] (ServerService Thread Pool -- 27)   at com.p6spy.engine.spy.P6ModuleManager.<clinit>(P6ModuleManager.java:61)
07:18:03,159 ERROR [stderr] (ServerService Thread Pool -- 27)   at com.p6spy.engine.spy.P6Core.initialize(P6Core.java:54)
07:18:03,160 ERROR [stderr] (ServerService Thread Pool -- 27)   at com.p6spy.engine.spy.P6SpyDriver.<init>(P6SpyDriver.java:61)
07:18:03,161 ERROR [stderr] (ServerService Thread Pool -- 27)   at com.p6spy.engine.spy.P6SpyDriver.<clinit>(P6SpyDriver.java:40)
07:18:03,162 ERROR [stderr] (ServerService Thread Pool -- 27)   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
07:18:03,163 ERROR [stderr] (ServerService Thread Pool -- 27)   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
07:18:03,164 ERROR [stderr] (ServerService Thread Pool -- 27)   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
07:18:03,165 ERROR [stderr] (ServerService Thread Pool -- 27)   at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
07:18:03,166 ERROR [stderr] (ServerService Thread Pool -- 27)   at org.jboss.as.connector.subsystems.datasources.JdbcDriverAdd.performRuntime(JdbcDriverAdd.java:135)
07:18:03,167 ERROR [stderr] (ServerService Thread Pool -- 27)   at org.jboss.as.controller.AbstractAddStepHandler$1.execute(AbstractAddStepHandler.java:50)
07:18:03,168 ERROR [stderr] (ServerService Thread Pool -- 27)   at org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:385)
07:18:03,169 ERROR [stderr] (ServerService Thread Pool -- 27)   at org.jboss.as.controller.AbstractOperationContext.doCompleteStep(AbstractOperationContext.java:272)
07:18:03,170 ERROR [stderr] (ServerService Thread Pool -- 27)   at org.jboss.as.controller.AbstractOperationContext.completeStep(AbstractOperationContext.java:200)
07:18:03,172 ERROR [stderr] (ServerService Thread Pool -- 27)   at org.jboss.as.connector.subsystems.datasources.DataSourceEnable$1.execute(DataSourceEnable.java:91)
07:18:03,174 ERROR [stderr] (ServerService Thread Pool -- 27)   at org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:385)
07:18:03,177 ERROR [stderr] (ServerService Thread Pool -- 27)   at org.jboss.as.controller.AbstractOperationContext.doCompleteStep(AbstractOperationContext.java:272)
07:18:03,179 ERROR [stderr] (ServerService Thread Pool -- 27)   at org.jboss.as.controller.AbstractOperationContext.completeStep(AbstractOperationContext.java:200)
07:18:03,189 ERROR [stderr] (ServerService Thread Pool -- 27)   at org.jboss.as.connector.subsystems.datasources.DataSourceEnable$1.execute(DataSourceEnable.java:91)
07:18:03,190 ERROR [stderr] (ServerService Thread Pool -- 27)   at org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:385)
07:18:03,193 ERROR [stderr] (ServerService Thread Pool -- 27)   at org.jboss.as.controller.AbstractOperationContext.doCompleteStep(AbstractOperationContext.java:272)
07:18:03,196 ERROR [stderr] (ServerService Thread Pool -- 27)   at org.jboss.as.controller.AbstractOperationContext.completeStep(AbstractOperationContext.java:200)
07:18:03,198 ERROR [stderr] (ServerService Thread Pool -- 27)   at org.jboss.as.controller.ParallelBootOperationStepHandler$ParallelBootTask.run(ParallelBootOperationStep
07:18:03,280 ERROR [stderr] (ServerService Thread Pool -- 27)   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
07:18:03,282 ERROR [stderr] (ServerService Thread Pool -- 27)   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
07:18:03,285 ERROR [stderr] (ServerService Thread Pool -- 27)   at java.lang.Thread.run(Thread.java:744)
07:18:03,287 ERROR [stderr] (ServerService Thread Pool -- 27)   at org.jboss.threads.JBossThread.run(JBossThread.java:122)
07:18:03,314 INFO  [org.jboss.as.connector.subsystems.datasources] (ServerService Thread Pool -- 27) JBAS010403: Deploying JDBC-compliant driver class com.p6spy.engine.sp
07:18:03,344 INFO  [org.jboss.as.connector.subsystems.datasources] (ServerService Thread Pool -- 27) JBAS010403: Deploying JDBC-compliant driver class oracle.jdbc.OracleD

**Comment by quintonm** [comment]
The appender that you have configured is in the wrong package.  It looks
like you are using settings from P6Spy 1.3.  You should start with the
default spy.properties at
https://p6spy.github.io/p6spy/2.0/configandusage.html.

**Comment by davutg** [comment]
Do you have any sugesstion for this stackoverflow.com/q/31337283/413032
