### ISSUE TITLE
Lazily create spy.log

### ISSUE THREAD

**Issue by felixbarny** [p6spy/p6spy#290]
Would it be possible to somehow lazily create the spy.log file? 

I want to change the appender at runtime by calling `P6SpyOptions.getActiveInstance().setAppender("my.Appender")`, but when I do that the spy.log file is created anyway. The problem stems from P6Spy loading configuration when P6SpyOptions.getActiveInstance() is called for the first time. Since the default appender is the FileLogger, it gets initialized before you change the appender.

Even when trying to set the appender via `System.setProperty`, the File is created when using wildfly. The problem ist, that wildfly initializes p6spy quite early on startup, because the DiverProcessor loads the P6SpyDriver which initializes the P6Core which leads to a creation of spy.log, because the FileLogger is the default appender. 

See also our discussion at https://github.com/p6spy/p6spy/issues/286#issuecomment-100589576

**Comment by felixbarny** [comment]
Nice :)

**Comment by quintonm** [comment]
Let me know if you have any problems with it.

BTW - Do you need any other changes to make it easier to integrate with
P6Spy?

**Comment by felixbarny** [comment]
Not directly a integration issue, but I'd prefer the execution time to be in nanoseconds rather than millis. Especially when working with embedded databases the SQL execution time often is 0. 

Also, it would be cool if p6spy would measure the number of returned rows. 

I think the execution time only includes the time of initial result (max fetch_size rows are returned). But not the time to scroll more rows. Is it possible to measure that time as well? Does that make sense?

**Comment by quintonm** [comment]
To capture execution time less than 1 ms, I have created
https://github.com/p6spy/p6spy/issues/295.

As for the fetch time, P6Spy records the time for the initial statement
execution as well as the time to move to the next record.  This should
capture the total time required to scroll through the entire result set.

**Comment by felixbarny** [comment]
Ok, that's good to know. Could you point me to the source? I'm curios about how that works.

Thx for creating the issues. It's awesome to see so much innovation in such a mature (not to say old :stuck_out_tongue_winking_eye:) project.

**Comment by quintonm** [comment]
The logging for ResultSet.next() happens in P6LogResultSetNextDelegate.

https://github.com/p6spy/p6spy/blob/master/src/main/java/com/p6spy/engine/logging/P6LogResultSetNextDelegate.java

**Comment by felixbarny** [comment]
Thx for the link. #295 probably is also a concern here.

How can I get the ResultSetInformation inside a P6Logger to log the count of returned rows?

**Comment by quintonm** [comment]
There is no support for that right now since the log message passed to the
logger doesn't have a reference to ResultSetInformation.  The
ResultSetInformation makes it as far as P6LogQuery.log(Category,Loggable).
It would not be too much work to pass the Loggable object all of the way to
the logger.

Feel free to enter an issue for the change and optionally a PR  :) .
