### ISSUE TITLE
Fix site publication problems

### ISSUE THREAD

**Issue by quintonm** [p6spy/p6spy#294]
Site publishing is currently disabled since it is causing the builds to fail.  The problem seems to be related to [this issue](https://github.com/github/maven-plugins/issues/17) in the github maven-site-plugin.

**Comment by quintonm** [comment]
It appears that the latest version of org.github.github:site-maven-plugin (0.12) has fixed this issue.

https://github.com/github/maven-plugins/commit/a202931faaf8895fbb176138d81d15bf1849653d

**Comment by quintonm** [comment]
The update to site-maven-plugin does solve the throttling issue.  However, it takes too long and travis times out after 10 minutes.  

Anyone have any ideas on what to do about site generation?

**Comment by typekpb** [comment]
@quintonm @felixbarny we publish docs via read the docs now, javadoc link is present as well => sounds like time to close this one. Any objections?

**Comment by quintonm** [comment]
Sounds good to me
