### ISSUE TITLE
Add option to report execution time less than 1 ms

### ISSUE THREAD

**Issue by quintonm** [p6spy/p6spy#295]
When using P6Spy with embedded databases, the execution time is normally reported as 0 ms.

**Comment by felixbarny** [comment]
To make this possible in a backwards compatible way, I'd suggest to add a configuration switch which by default is configured to use `System.currentTimeMillis()` and can be set to use `System.nanoTime`

**Comment by typekpb** [comment]
@felixbarny Agree! New property feature switch would do it. Willing to
submit pull request?

**Comment by felixbarny** [comment]
Sure, I'm currently working on it.

**Comment by typekpb** [comment]
Perfect, thanks!
