### ISSUE TITLE
Allow for lazy initialization of P6Spy

### ISSUE THREAD

**Issue by quintonm** [p6spy/p6spy#297]
Due to the auto-registration of of the JDBC driver through META-INF/servers/java.sql.Driver, P6Spy is initialized very early preventing changing the configuration via API calls before initialization.  This becomes a problem for third party libraries/frameworks that use P6Spy ( [StageMonitor](https://github.com/stagemonitor/stagemonitor) is a good example) as they do not have any control over the JDBC URL, DataSource configuration, or spy.properties.

#290 allowed for FileLogger to be initialized lazily to avoid spy.log from being created when P6Spy initialized with default configuration.  However, the real solution would be to delay initialization until the initial configuration can be provided.  This would eliminate the need to force P6Spy to reload with modified configuration.

Right now, I think that this can be achieved by delaying initialization of P6Spy until the first connection is obtained.  However, I am open to any and all suggestions on this issue.

**Comment by felixbarny** [comment]
Sounds good!

**Comment by felixbarny** [comment]
With p6spy 3.0, stagemonitor doesn't use p6spy core anymore: https://github.com/stagemonitor/stagemonitor/commit/85533b63a8f7f9c6a2eeeb1dee08f8ce777296d4#diff-0af5673cff6db313eef868864495df38R47. One advantage is that it doesn't interfere with p6spy when someone uses both stagemonitor and p6spy. So initializing p6spy eagerly even if it does not have to be initialized at all when used only with stagemonitor is not necessary.
