### ISSUE TITLE
Support of reacting differently on SQL-Errors within datasource-proxy

### ISSUE THREAD

**Issue by Heimschmiede** [p6spy/p6spy#299]
#### Enhancement

In my UseCase I want to log only the SQLs that fail on the database. Right now (Maven-Version 2.1.4) my custom logger cannot distinguish if the given sql was executed fine or failed.

If my logger gets to know if the execution failed it can log the corresponding sql with log-level error. If it worked fine it can use log-level debug.

#### Related Code

I am using the `P6DataSource` and the failure can then be detected in `P6LogPreparedStatementExecuteDelegate:50` . The `finally` statement can be replaced by a `catch`-statement. The call to `P6LogQuery` can then be done at the end of the try-block (success-case) and within the catch-block (error-case).

#### Proposed solutions

1. Using error-category in case of a failure. But then the logger cannot see errors on rollback-actions for instance.
2. An additional parameter in the `logSQL`-method of the logger that indicates if an error occured
3. A new method in the logger that is called on errors with the effective sql as a parameter. (The currently available method logException is either called never or on all statement-executions)

**Comment by quintonm** [comment]
I think that adding the concept of events might be a better solution than using a custom logger.  I am not sure where the entry point would be just yet.  However, you would need an interface to register a listener for the events that you are interested in.  The event would have all of the same information that is sent to the logger plus additional information such as the exception in the event of a failure.  Would this work for your use case?

**Comment by Heimschmiede** [comment]
yes, that would work in my use case.

**Comment by quintonm** [comment]
Events have been added in 3.0.  Instead of adding a logger, you will add an event listener.  The listener will be passed the SQLException (if any) along with all of the information needed for logging.
