### ISSUE TITLE
error when included as a dependency in maven project.

### ISSUE THREAD

**Issue by ravshansbox** [p6spy/p6spy#300]
Following error is being logged when included in maven project:
The POM for p6spy:p6spy:jar:2.1.4 is invalid, transitive dependencies (if any) will not be available.

**Comment by ravshansbox** [comment]
This is output with debug logging enabled:
[WARNING] The POM for p6spy:p6spy:jar:2.1.4 is invalid, transitive dependencies (if any) will not be available: 1 problem was encountered while building the effective model for p6spy:p6spy:2.1.4
[ERROR] 'dependencies.dependency.systemPath' for p6spy:p6spy-signedjar-test:jar must specify an absolute path but is ${basedir}/src/test/resources/p6spy-signedjar-test-1.0.0.jar @

**Comment by Stephan972** [comment]
This same error is still present in p6spy 2.2.0

**Comment by Stephan972** [comment]
See PR #311
