### ISSUE TITLE
Implement logging pattern.

### ISSUE THREAD

**Issue by ravshansbox** [p6spy/p6spy#301]
Implement logging pattern.

End-user should supply log pattern instead of implementing Interface just for setting up logging format.

**Comment by tomikmar** [comment]
It would be great if there was possibility to specify log format in spy.properties. Maybe one of MessageFormattingStrategy implementations could use spy.properties to format output?

**Comment by typekpb** [comment]
@tomikmar @ravshansbox pull requests welcome

**Comment by typekpb** [comment]
implemented in: #391 => closing
