### ISSUE TITLE
Get the ResultSetInformation inside a P6Logger to log the count of returned rows

### ISSUE THREAD

**Issue by felixbarny** [p6spy/p6spy#307]
As discussed in #290, it would be great to be able to get the number of returned rows inside a P6Logger.

**Comment by felixbarny** [comment]
Unfortunately, the change would introduce a breaking change to the `P6Logger` interface. So this would probably go into 3.0. This is a great resource about how to design SPIs which enable you to extend them in the future: http://blog.jooq.org/2015/05/21/do-not-make-this-mistake-when-developing-an-spi/

**Comment by quintonm** [comment]
Duplicates #298
