### ISSUE TITLE
Make build compatible with Java 7

### ISSUE THREAD

**Issue by Stephan972** [p6spy/p6spy#309]
The maven compiler plugin is told to compile Java 6 code.

However, the code contains references to methods only available as of Java 7.

The following PR addresses this: https://github.com/Stephan972/p6spy/pull/1.

**Comment by typekpb** [comment]
Thanks for your contributions. Would you mind creating pull requests to original repo (this one), rather than your fork?

**Comment by Stephan972** [comment]
Sorry, Github is all a new thing for me. 

How can I move the pull requests from my fork to original repo?

**Comment by Stephan972** [comment]
PR #310

**Comment by quintonm** [comment]
Which methods are only available in Java 7?  We are setting the compiler
plugin to generate Java 6 compatible byte code so that it can still be used
in environments what have not upgraded to Java 7 or later.

**Comment by Stephan972** [comment]
@quintonm 
>Which methods are only available in Java 7?
getParentLogger is available since Java 7

See https://docs.oracle.com/javase/7/docs/api/javax/sql/CommonDataSource.html#getParentLogger()

**Comment by Stephan972** [comment]
Here are all errors the Eclipse Java 6 compiler reports:

**The method getParentLogger() is undefined for the type DataSource**
> P6DriverManagerDataSource.java
/p6spy/src/main/java/com/p6spy/engine/spy
line 122

**AutoCloseable cannot be resolved to a type**
>P6WrapperUnwrapDelegateTest.java
/p6spy/src/test/java/com/p6spy/engine/common
line 64

**The method getParentLogger() of type DataSourceTest.TestBasicDataSource must override or implement a supertype method**
>DataSourceTest.java
/p6spy/src/test/java/com/p6spy/engine/spy
line 212

**The method unwrap(Class<AutoCloseable>) from the type Wrapper refers to the missing type**
>AutoCloseable
P6WrapperUnwrapDelegateTest.java
/p6spy/src/test/java/com/p6spy/engine/common
line 64

**AutoCloseable cannot be resolved to a type**
>P6WrapperUnwrapDelegateTest.java
/p6spy/src/test/java/com/p6spy/engine/common
line 64

**The method getNetworkTimeout() of type TestConnectionImpl must override or implement a supertype method**
>TestConnectionImpl.java
/p6spy/src/test/java/com/p6spy/engine/test
line 297

**The method abort(Executor) of type TestConnectionImpl must override or implement a supertype method**
>TestConnectionImpl.java
/p6spy/src/test/java/com/p6spy/engine/test
line 287

**The method setNetworkTimeout(Executor, int) of type TestConnectionImpl must override or implement a supertype method**
>TestConnectionImpl.java
>/p6spy/src/test/java/com/p6spy/engine/test
>line 292

**The method setSchema(String) of type TestConnectionImpl must override or implement a supertype method**
>TestConnectionImpl.java
>/p6spy/src/test/java/com/p6spy/engine/test
>line 277

**The method getSchema() of type TestConnectionImpl must override or implement a supertype method**
>TestConnectionImpl.java
>/p6spy/src/test/java/com/p6spy/engine/test
>line 282

**The method getParentLogger() of type P6DataSource must override or implement a supertype method**
>P6DataSource.java
>/p6spy/src/main/java/com/p6spy/engine/spy
>line 313

**The method getParentLogger() is undefined for the type CommonDataSource**
>P6DataSource.java
>/p6spy/src/main/java/com/p6spy/engine/spy
>line 314

**Comment by quintonm** [comment]
I see now.  The Java 7 methods are in test code and classes which could not
be implemented via proxy.  In these cases, you do need Java 7 to compile
but runtime only needs Java 6.  For this reason, the compiler should be
left at 1.6 instead of moving to 1.7.

**Comment by Stephan972** [comment]
@quintonm Isn't it possible to compile with Java 7 but generate Java 6 target code?

**Comment by quintonm** [comment]
@Stephan972 Yes, it is certainly possible to compile using Java 7 and generate Java 6 target code.  This is what that `java.build` property is controlling in `pom.xml`.  That is being used by the maven compiler plugin to generate bytecode for that version of java.

```
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.1</version>
        <configuration>
          <source>${java-build}</source>
          <target>${java-build}</target>
        </configuration>
      </plugin>
```

This allows for us to build using Java 7 (required since DataSource has new methods in Java 7) and still produce byte code which runs on Java 6.  

If you change the value of `java.build` to 1.7, then it will produce byte code that only runs on Java 7 and later.  Since we are still supporting Java 6, it needs to remain at 1.6 for now.

**Comment by Stephan972** [comment]
What about this:

    <properties>
         <java-build>1.7</java-build>
         <java-run>1.6</java-run>
    </properties>

    <source>${java-build}</source>
    <target>${java-run}</target>

**Comment by quintonm** [comment]
Unfortunately, that doesn't work.  Source must be equal to or less than the
target.

javac -source 1.7 -target 1.6 com/p6spy/engine/common/ClassHasher.java
javac: source release 1.7 requires target release 1.7

The end result here is that if you want to produce bytecode which runs on a
1.6 JVM, you can not use any 1.7 language features.

**Comment by Stephan972** [comment]
@quintonm 
>Unfortunately, that doesn't work.  Source must be equal to or less than the
target.

I always knew it didn't work. But I never had a chance to know why. Now, I know...
Thanks :)

**Comment by quintonm** [comment]
Here is a more descriptive explanation of why it doesn't work.

http://stackoverflow.com/questions/17168184/java-7-language-backwards-compatibility

BTW - I had to look this up myself.  I had never tried setting the source
compatibility higher than the target version.

**Comment by felixbarny** [comment]
This issue should be closed I guess
