### ISSUE TITLE
Remove throws SQLException declaration on P6Core.wrapConnection

### ISSUE THREAD

**Issue by felixbarny** [p6spy/p6spy#313]
The only call in `P6Core.wrapConnection` that can throw a `SQLException` is `com.p6spy.engine.spy.P6Factory#getConnection`. But none of the actual implementations can throw this exception.

Removing the throws declaration would ease calls to `P6Core.wrapConnection` when using it inside methods which do not declare a `SQLException` themselves like in `org.eclipse.persistence.sessions.Connector#connect`.

**Comment by bhemar** [comment]
Hi, can you please check my pull request? Do you have any comments?

**Comment by felixbarny** [comment]
@bhemar: looks good to me now. Time to create a pull request!

**Comment by quintonm** [comment]
solved by PR #315
