### ISSUE TITLE
Add support for events

### ISSUE THREAD

**Issue by quintonm** [p6spy/p6spy#319]
For applications extending/wrapping P6Spy, a better integration than simply adding a logger implementation is needed.  For example, if an application wants to aggregate the execution time of a prepared statement execution along with the associated calls to ResultSet.next(), the only option is to parse the log messages emitted through the logger.  Likewise, it is also not currently possible to get the number of returned rows through the logger since that information is not available at that level.

The only other integration point currently is to add a new module.  This would provide unlimited functionality (even the ability to modify the JDBC statements).  However, it means that the application would need to provide its own implementation of all of the interceptors.

I think that a better integration point would be through events.  Applications which are extending/wrapping P6Spy could simply register listeners for the various events that they care about.  The data in the event would contain pretty much everything collected by the interceptors.

The current logging and outage modules could be refactored to listen for events as well.  This would remove the code duplication between the modules.

This could be a possible solution for the following issues:
#299 
#298 
#295

**Comment by felixbarny** [comment]
This sounds like a great idea! But I'm still not sure how to tell which event is the last one for one DB call. This would be crutial for being able to aggregate the events of one interaction.

**Comment by quintonm** [comment]
It would be the event generated by ResultSet.close().

**Comment by typekpb** [comment]
Well, for the resource leak, this could be never called, I guess.
However, this could be something p6spy could help in detecting. To me it
sounds like a candidate for a new module (similar to outage).
On May 7, 2016 03:28, "Quinton McCombs" <notifications@github.com> wrote:

It would be the event generated by ResultSet.close().


On Thu, May 5, 2016 at 1:17 AM, Felix <notifications@github.com> wrote:

> This sounds like a great idea! But I'm still not sure how to tell which
> event is the last one for one DB call. This would be crutial for being
able
> to aggregate the events of one interaction.
>
> —
> You are receiving this because you authored the thread.

> Reply to this email directly or view it on GitHub
> <https://github.com/p6spy/p6spy/issues/319#issuecomment-217083555>

>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/p6spy/p6spy/issues/319#issuecomment-217596770>

**Comment by felixbarny** [comment]
I have found a way for my usecase to consider the time for all events: https://github.com/stagemonitor/stagemonitor/commit/af0c355d1053d2b44af48b7942c4fe28a6638881

**Comment by quintonm** [comment]
I really see the event system as being in the core of P6Spy with the modules just responding to events.  This would allow for a single set of interceptors which would reduce some of the code duplication between modules.
