### ISSUE TITLE
 P6spy 1.1 works but P6spy 2.3 does not register

### ISSUE THREAD

**Issue by alexcalaguag** [p6spy/p6spy#322]
I am using the spy 1.1 and works correctly. I wanted to test the new version has other features.
I downloaded the spy 2.3 Maven Central . I made the settings in the file in the new format and does not create the log file and does not throw error 

This is my configuration and my archive spy.properties (2.3):
Enviroment = apache-tomcat-7.0.65, java 1.7
#################################################################
MODULES   #
################################################################
**modulelist=com.p6spy.engine.spy.P6SpyFactory,com.p6spy.engine.logging.P6LogFactory,com.p6spy.engine.outage.P6OutageFactory**

################################################################
 CORE (P6SPY) PROPERTIES                                      #
################################################################
// A comma separated list of JDBC drivers to load and register.
// (default is empty)
//
// Note: This is normally only needed when using P6Spy in an
// application server environment with a JNDI data source or when
// using a JDBC driver that does not implement the JDBC 4.0 API
**driverlist=oracle.jdbc.driver.OracleDriver**

// for flushing per statement
// (default is false)
**autoflush = true**

// sets the date format using Java's SimpleDateFormat routine. 
// In case property is not set, miliseconds since 1.1.1970 (unix time) is used (default is empty)
// dateformat=

// prints a stack trace for every statement logged
//stacktrace=false
// if stacktrace=true, specifies the stack trace to print
//stacktraceclass=

// determines if property file should be reloaded
// Please note: reload means forgetting all the previously set
// settings (even those set during runtime - via JMX)
// and starting with the clean table 
// (default is false)
//reloadproperties=false

// determines how often should be reloaded in seconds
// (default is 60)
//reloadpropertiesinterval=60

//specifies the appender to use for logging
// Please note: reload means forgetting all the previously set
// settings (even those set during runtime - via JMX)
//and starting with the clean table 
// (only the properties read from the configuration file)
// (default is com.p6spy.engine.spy.appender.FileLogger)
//appender=com.p6spy.engine.spy.appender.Slf4JLogger
//appender=com.p6spy.engine.spy.appender.StdoutLogger
**appender=com.p6spy.engine.spy.appender.FileLogger**

//name of logfile to use, note Windows users should make sure to use forward slashes in their //pathname (e:/test/spy.log) 
// (used for com.p6spy.engine.spy.appender.FileLogger only)
// (default is spy.log)
**logfile = c:/log/spy.log**

//append to the p6spy log file. if this is set to false the
// log file is truncated every time. (file logger only)
// (default is true)
**append=true**

// class to use for formatting log messages (default is: //com.p6spy.engine.spy.appender.SingleLineFormat)
//logMessageFormat=com.p6spy.engine.spy.appender.SingleLineFormat

// format that is used for logging of the date/time/... (has to be compatible with //java.text.SimpleDateFormat)
// (default is dd-MMM-yy)
//databaseDialectDateFormat=dd-MMM-yy

// whether to expose options via JMX or not
// (default is true)
//jmx=true

// if exposing options via jmx (see option: jmx), what should be the prefix used?
// jmx naming pattern constructed is: com.p6spy(.<jmxPrefix>)?:name=<optionsClassName>
// please note, if there is already such a name in use it would be unregistered first (the last // //registered wins)
// (default is none)
//jmxPrefix=

// if set to true, the execution time will be measured in nanoseconds as opposed to milliseconds
// (default is false)
//useNanoTime=false

#################################################################
# DataSource replacement                                        #
#################################################################
//realdatasource=/RealMySqlDS
//realdatasourceclass=com.mysql.jdbc.jdbc2.optional.MysqlDataSource

#################################################################
# DataSource properties                                         #
#################################################################
//ealdatasourceproperties=port;3306,serverName;myhost,databaseName;jbossdb,foo;bar

#################################################################
# JNDI DataSource lookup                                           #
#################################################################
//jndicontextfactory=org.jnp.interfaces.NamingContextFactory
//jndicontextproviderurl=localhost:1099
//jndicontextcustom=java.naming.factory.url.pkgs;org.jboss.nameing:org.jnp.interfaces

//jndicontextfactory=com.ibm.websphere.naming.WsnInitialContextFactory
//jndicontextproviderurl=iiop://localhost:900

################################################################
// P6 LOGGING SPECIFIC PROPERTIES                               #
################################################################

// filter what is logged
// please note this is a precondition for usage of: include/exclude/sqlexpression
// (default is false)
//filter=false

// comma separated list of strings to include
// please note that special characters escaping (used in java) has to be done for the provided //regular expression
// (default is empty)
//include =
// comma separated list of strings to exclude
// (default is empty)
//exclude =

// sql expression to evaluate if using regex
// please note that special characters escaping (used in java) has to be done for the provided regular expression
// (default is empty)
//sqlexpression = 

//list of categories to exclude: error, info, batch, debug, statement,
//commit, rollback and result are valid values
//(default is info,debug,result,resultset,batch)
//excludecategories=info,debug,result,resultset,batch

// Execution threshold applies to the standard logging of P6Spy.       
// While the standard logging logs out every statement          
// regardless of its execution time, this feature puts a time   
// condition on that logging. Only statements that have taken   
// longer than the time specified (in milliseconds) will be     
// logged. This way it is possible to see only statements that  
// have exceeded some high water mark.                          
// This time is reloadable.                                     
// executionThreshold=integer time (milliseconds)
/// (default is 0)
//executionThreshold=

################################################################
// P6 OUTAGE SPECIFIC PROPERTIES                                #
################################################################
// Outage Detection
// outagedetection=true|false
// outagedetectioninterval=integer time (seconds)
//
// (default is false)
//outagedetection=false
// (default is 60)
//outagedetectioninterval=30

**Comment by quintonm** [comment]
What does your JDBC connection URL look like?

**Comment by quintonm** [comment]
Can you post the contents of that file or just the JDBC URL?

**Comment by alexcalaguag** [comment]
I'm sorry, had put the xml characters and that's why not appeared complete message

**Comment by quintonm** [comment]
Ah, I see now.

jdbc:oracle:thin:@//LOCALHOST:1521/XE


With 2.X, you will need to modify the JDBC URL as described at the
following location.

http://p6spy.github.io/p6spy/2.0/install.html#tomcat

**Comment by quintonm** [comment]
If you are still having problems, please reopen.

**Comment by alexcalaguag** [comment]
Thank you for your help @quintonm  uintonm and sorry for taking en answer
