### ISSUE TITLE
log row count and SQLException

### ISSUE THREAD

**Issue by auntyellow** [p6spy/p6spy#323]
Row count and SQLException can tell us whether an SQL statement is successfully executed.

We may extend P6Logger interface like this:

    public void logSQL(int connectionId, String now, long elapsed, Category category, String prepared, String sql, int updateCount, SQLException e);

And P6LogResultSetDelegate/P6LogElapsedDelegate may be like this:

    int updateCount = 0;
    SQLException sqle = null;
    try {
      Object result = method.invoke(underlying, args);
      if (result instanceof Number) {
        updateCount = ((Number) result).intValue();
      }
      return result;
    } catch (SQLException e) {
      sqle = e;
      throw e;
    } finally {
      P6LogQuery.logElapsed(loggable.getConnectionId(), startTime, category, loggable, updateCount, sqle);
    }

**Comment by quintonm** [comment]
This is supported by adding an event listener.
