### ISSUE TITLE
OraclePreparedStatement set parameter by name, throws ClassCastException

### ISSUE THREAD

**Issue by kavai77** [p6spy/p6spy#338]
I use `oracle.jdbc.pool.OracleDataSource` as a realdatasourceclass of P6DataSource
When I try to set parameter by name using 
```
OraclePreparedStatement stmt = (OraclePreparedStatement) conn.prepareStatement(sql);
stmt.setObjectAtName("firstName", "John", Types.VARCHAR);
```
I get an exception:
```
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
        at com.p6spy.engine.logging.P6LogPreparedStatementSetParameterValueDelegate.invoke(P6LogPreparedStatementSetParameterValueDelegate.java:39) ~[p6spy-2.3.1.jar:na]
        at com.p6spy.engine.proxy.GenericInvocationHandler.invoke(GenericInvocationHandler.java:116) ~[p6spy-2.3.1.jar:na]
        at com.p6spy.engine.proxy.P6Proxy$$EnhancerByCGLIB$$5858edb0.setObjectAtName(<generated>) ~[p6spy-2.3.1.jar:na]
```

**Comment by felixbarny** [comment]
I think the error stems from the fact that all `set*` methods are intercepted and are expected to have an `Integer` as the first parameter. This should however be fixed in 3.0.0-alpha-1, although you won't be able to cast the statement to `OraclePreparedStatement` anymore. Instead, you have to unwrap it. See also https://github.com/p6spy/p6spy/blob/master/src/site/markdown/3.0/knownissues.md.

Could you give 3.0.0-alpha-1 a shot to see if it works for you?

**Comment by kavai77** [comment]
Hi Felix,
Thank you for this very quick answer, I have tried out 3.0.0-alpha-1 with unwrapping the `OraclePreparedStatement` and it works fine! Thanks once again!

**Comment by felixbarny** [comment]
Great :) You are very welcome!

**Comment by kavai77** [comment]
Just one more question: do you have a timeline or plan when a stable version of 3.0.0 is released? Thanks...

**Comment by quintonm** [comment]
I think that it might be a month or more before the final release of
3.0.0.  We are still debating some breaking changes to some interfaces and
removal of deprecated methods.

It would want to stay with a more stable release until 3.0.0 is ready, you
can continue to use 2.3.1.  You can still unwrap in 2.3.1 to avoid the
problem with the proxy.

**Comment by kavai77** [comment]
I just tried out unwrapping `OraclePreparedStatement `with 2.3.1, and unfortunately it does not work. This is the reason:
**2.3.1**
> PreparedStatement stmt = conn.prepareStatement(sql)
> stmt.getClass() // returns: oracle.jdbc.internal.OracleStatement$$EnhancerByCGLIB$$1722af40
> stmt instanceOf OraclePreparedStatement // return true, also
> stmt == stmt.unwrap(OraclePreparedStatement.class) // returns true
> stmt.unwrap(OraclePreparedStatement.class).setObjectAtName("name", "value"); // throws exception

Fortunately in 3.0.0-alpha-1 works well with the following differences:
**3.0.0-alpha-1**
> PreparedStatement stmt = conn.prepareStatement(sql)
> stmt.getClass() // returns: com.p6spy.engine.wrapper.PreparedStatementWrapper
> stmt instanceOf OraclePreparedStatement // return false, therefore
> stmt == stmt.unwrap(OraclePreparedStatement.class) // returns false
> stmt.unwrap(OraclePreparedStatement.class).setObjectAtName("name", "value"); // works fine
