### ISSUE TITLE
SQLException logging

### ISSUE THREAD

**Issue by kavai77** [p6spy/p6spy#339]
I want to log the p6spy events into another file which can be configured by my SLF4J provider. 
Whenever a `SQLException` happens, I can see it in my regular application logs, but p6spy is silent about that. 
p6spy only logs the erroneous SQL statement, but it does not log whether the execution was successful or erroneous.
Is there a solution for that?

**Comment by quintonm** [comment]
Not without writing some code....

In 3.0.0-alpha-1 we added the concept of events.  The logging module has a listener that responds to those events by writing out the log messages with the SQL statement.  The idea is that the event mechanism would be an extension point for applications embedding p6spy.

In 3.0.0-alpha-2 we are adding an easy way to register listeners and be able to replace the listener used by the logging module.  If you want to also log the SQL exception right along with the sql statement, you should be able to include a subclass of LoggingEventListener which logs the exception.  You would then need to direct messages from your subclass of the listener to the same log file where the sql statements are being written.

The functionality is being added with PR # 336.   Please take a look and see if this would meet your needs.  Feedback is always welcome!

**Comment by kavai77** [comment]
Thanks for your explanation., I went through the discussions of the pull request, too, and it seems quite reasonable for me. I like the way that I will be able to extend `LoggingEventListener` and register my listener instead of the original one.
Also I like the interface, too, because I am going to receive both `Loggable` and `SQLException`, so I will be able to log into the same line the SQL statement with values and whether the execution was successful or not. Your work is so much appreciated, thank!

**Comment by quintonm** [comment]
@kavai77 - Just FYI - We released 3.0.0-alpha-2 as 3.0.0-rc-1.
