### ISSUE TITLE
Fix build failure

### ISSUE THREAD

**Issue by quintonm** [p6spy/p6spy#342]
As mentioned in this PR [comment](https://github.com/p6spy/p6spy/pull/336#issuecomment-239091638), the build is failing because of firebird.

@typekpb suggests a fix in this [comment](https://github.com/p6spy/p6spy/pull/336#issuecomment-239111815).

**Comment by quintonm** [comment]
Note: This problem started for no apparent reason.

**Comment by felixbarny** [comment]
Unfortunately, this suggestion does not seem to work: https://github.com/p6spy/p6spy/pull/341

**Comment by quintonm** [comment]
It did fix firebird but we then ran into another problem:
```
0.11s$ script/travis/before_script_firebird.sh
ISQL Version: LI-V2.5.1.26351 Firebird 2.5
Use CONNECT or CREATE DATABASE to specify a database
before_script.2
0.01s$ script/travis/before_script_mysql.sh
1.93s$ script/travis/before_script_postgres.sh
CREATE DATABASE
/etc/postgresql/9.1/main ~/build/p6spy/p6spy
~/build/p6spy/p6spy
 * Restarting PostgreSQL 9.1 database server       * The PostgreSQL server failed to start. Please check the log output:
2016-08-12 09:27:04 UTC LOG:  could not translate host name "localhost", service "5432" to address: Name or service not known
2016-08-12 09:27:04 UTC WARNING:  could not create listen socket for "localhost"
2016-08-12 09:27:04 UTC FATAL:  could not create any TCP/IP sockets
fail]
```

**Comment by quintonm** [comment]
Wow, they have totally hosed up travis builds!

```
cat /etc/hosts
127.0.0.1 testing-gce-5a224028-6199-4703-906a-94fea303af10 testing-gce-5a224028-6199-4703-906a-94fea303af10
127.0.0.1 localhost  precise64 nettuno travis vagrant
127.0.1.1 testing-gce-5a224028-6199-4703-906a-94fea303af10 testing-gce-5a224028-6199-4703-906a-94fea303af10
127.0.1.1 localhost precise64 nettuno travis vagrant
```

Notice that localhost has two entries....

**Comment by typekpb** [comment]
well, could it have something to do with our workaround we applied previously: 77f7cb9 ?
Maybe rolling back that one an giving it a retry could help.

**Comment by quintonm** [comment]
Well, rolling that fix back resulted in an identical hosts file.  I am guessing that the samne fix was added to the travis ci chef scripts.

However, after rolling back that change the build actually worked.  I am not sure what this means.  I have also reverted the change to the firebird script making the only change the revert of 77f7cb9.
If this one works, I will submit a PR.
