### ISSUE TITLE
mockito dependency should have a 'test' scope

### ISSUE THREAD

**Issue by auntyellow** [p6spy/p6spy#352]
I'm using 3.0.0-rc2 in my project but I do not like to have mockito jars in my war file so I have to exclude them in my pom.xml:

		<dependency>
			<groupId>p6spy</groupId>
			<artifactId>p6spy</artifactId>
			<version>3.0.0-rc2</version>
			<exclusions>
				<exclusion>
					<artifactId>mockito-core</artifactId>
					<groupId>org.mockito</groupId>
				</exclusion>
			</exclusions>
		</dependency>

**Comment by typekpb** [comment]
@auntyellow thanks for reporting!
