### ISSUE TITLE
SQL-Dates are not correctly logged

### ISSUE THREAD

**Issue by Clemens85** [p6spy/p6spy#360]
Hi there,

I am currently using P6Spy in latest stable version (2.3.1) and I intercept my database calls that are performed with Hibernate to a PostgreSQL database 9.5.

All works fine, except the logging of SQL-Dates, they seem to be not valid.
An example:
I have a table with a column declared as SQL Date. Let's assume the value of this column is the date of today (2016-10-20).  When I now insert data from my application and look e.g. at the generated INSERT or UPDATE statements then this date is logged exactly as '20-Okt-16', which is however a german date format. 
Due to this, the generated statements are not valid any more, so I cannot use the generated statements and execute them against a database. I am quite sure that this is also not the date-format that is used when I run my code that inserts data to the database, so I assume that maybe P6Spy does some reformatting?

Is there any trick to get the correct dates logged? I saw that there exist a dateformat configuration in spy.properties, but this only affects the timestamp of the logging itself but not the SQL statements.

Best regards,
Clemens

**Comment by felixbarny** [comment]
You have to configure `databaseDialectDateFormat`. Default is `dd-MMM-yy`. You will probably need dd-MM-yy

**Comment by Clemens85** [comment]
Oh sry for this stupid issue! This was indeed the setting I was missing (I just saw the other setting for log format itself). Thanks!

Just one additional note: The issue is solved for me now, but with this configuration option you can not distinguish between dates that have time (and zone) information and dates that are just LocalDates. 
But anyway this is a quite cumbersome topic for itself...

Best regards,
Clemens
