### ISSUE TITLE
register an event handler

### ISSUE THREAD

**Issue by soahc** [p6spy/p6spy#362]
Hi. The release notes of Version 3.0.0-alpha-1 specify that support for events has been added. Unfortunately I dont find any information about it in the documentation. How can I register an event handler which will be notified on the various JDBC events?

Thank you and kind regards. Philipp

**Comment by felixbarny** [comment]
You're right. That's not in the official docs yet. But You can take look at the Javadoc of [JdbcEventListener](https://github.com/p6spy/p6spy/blob/master/src/main/java/com/p6spy/engine/event/JdbcEventListener.java).

**Comment by soahc** [comment]
Thats great. Thank you very much.

**Comment by typekpb** [comment]
sounds like a question has been answered => closing
