### ISSUE TITLE
NullPointerException  at com.p6spy.engine.outag.OutageJdbcEventListener.onAfterCommit

### ISSUE THREAD

**Issue by markieww** [p6spy/p6spy#363]
![p6spy-outage](https://cloud.githubusercontent.com/assets/12639609/20626876/c4ba70bc-b31c-11e6-87d2-2291bdb1c229.png)

* OutageModule is activated and configured

Version 3.0.0

**Comment by typekpb** [comment]
Is it something sporadic, or is it easily reproducible? If reproducible, any chance for some working sample/test code?

**Comment by typekpb** [comment]
Original `P6OutageDetector` singleton implementation seemed buggy. As refactoring happened in #420 it should be fixed now. Feel free to reopen once you face the issue again.
