### ISSUE TITLE
Why was the last print twice?

### ISSUE THREAD

**Issue by strivezsh** [p6spy/p6spy#368]
![image](https://cloud.githubusercontent.com/assets/1477474/22910543/9ea2a292-f295-11e6-95c8-0cf2eb60b453.png)
why
![image](https://cloud.githubusercontent.com/assets/1477474/22910603/05b3daa0-f296-11e6-86d2-19e389e194a7.png)

**Comment by felixbarny** [comment]
The first two logs result from the `addBatch` calls.
The last one comes from `executeBatch` and the time also refers to the actual execution of the batched statement.

**Comment by strivezsh** [comment]
thanks
But I don't want to print the last one
What should I do?

**Comment by felixbarny** [comment]
But then you don't know the execution time of the statement. Is this really not important for you?

Anyway, if you don't want this behavior extend `LoggingEventListener` like this:

```
public class DontLogExecuteBatchEventListener extends LoggingEventListener {
	@Override
	public void onAfterExecuteBatch(StatementInformation statementInformation, long timeElapsedNanos, int[] updateCounts, SQLException e) {
	}
}
```

And follow the instruction of `LoggingEventListener`'s [javadoc](https://github.com/p6spy/p6spy/blob/master/src/main/java/com/p6spy/engine/logging/LoggingEventListener.java#L34) to register your custom event listener.

**Comment by strivezsh** [comment]
Thanks so much

**Comment by felixbarny** [comment]
You are very welcome :)

**Comment by zuisong** [comment]
May be we could add a config control whether to print the last one?
