### ISSUE TITLE
resultset category undocumented

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [p6spy/p6spy#369]
Here is what the [documentation](http://p6spy.readthedocs.io/en/latest/configandusage.html) tells about:

The log includes category information that describes the type of statement. This property excludes the listed categories. Valid options include the following:

- error includes P6Spy errors. (It is recommended that you include this category.)
- info includes driver startup information and property file information.
- debug is only intended for use when you cannot get your driver to work properly, because it writes everything.
- statement includes Statements, PreparedStatements, and CallableStatements.
- batch includes calls made to the addBatch() JDBC API.
- commit includes calls made to the commit() JDBC API.
- rollback includes calls made to the rollback() JDBC API.
- result includes statements generated by ResultSet.

What about `resultset`?

It traces very long output when inserting/updating binary data, and I don't know how to exclude it.

**Comment by typekpb** [comment]
@DavidPerezIngeniero thanks for report!

> What about resultset?

You're right we miss `resultset` there. Obviously we miss more than just that one, we'll provide an update.

> It traces very long output when inserting/updating binary data, and I don't know how to exclude it.

If binary data is something you fight with for inserts/updates I don't think we have specific category for that.

@quintonm @felixbarny it seems we should handle `byte[]` in a specific way (see `PreparedStatementInformation`): 

      protected String convertToString(Object value) {
           ...
           } else if (value instanceof byte[]) {
             result = toHexString((byte[]) value);
           }

Ideas for new category name? How about: `bytes`/`binary` ? We should probably respect it in `CallableStatementInformation`, `PreparedStatementInformation`, `StatementInformation` as well as `ResultSetInformation`.

Ideas?

**Comment by DavidPerezIngeniero** [comment]
`binary` is clear for me.

**Comment by felixbarny** [comment]
I'm not sure a `Category` is appropriate for this as it is specific to logging. `*StatementInformation` should not know about the existence of the `com.p6spy.engine.logging` package.

Maybe add a config switch to exclude converting binary parameters to string?

**Comment by DavidPerezIngeniero** [comment]
+1

**Comment by typekpb** [comment]
@felixbarny OK, well it would probably just passed as a switch down to *StatementInformation. 
Anyway, we can name it separately in config.
Ideas for config switch name?
`excludebinary=true|false # default is false`

**Comment by felixbarny** [comment]
> OK, well it would probably just passed as a switch down to *StatementInformation. Anyway, we can name it separately in config.

Not quite sure what you mean by that. Do you mean as opposed to retrieve the config within `*StatementInformation`?

I'm ok with `excludebinary`

**Comment by typekpb** [comment]
well, I just ment, that `*StatementInformation` doesn't have to know about `com.p6spy.engine.logging` package in any of the solutions proposed (neither `excludebinary=true` nor `excludecategories=binary,...`). 

But new switch is OK with me.

**Comment by felixbarny** [comment]
How would `excludecategories=binary` work then? By adding a flag to `com.p6spy.engine.common.Loggable#getSqlWithValues` and passing it in `com.p6spy.engine.common.P6LogQuery#logElapsed(int, long, com.p6spy.engine.logging.Category, com.p6spy.engine.common.Loggable)` like `doLogElapsed(connectionId, timeElapsedNanos, category, sql, loggable.getSqlWithValues(isBinaryExcluded(category)))`?

The advantage of the config flag would be that it does not only work for logging.

**Comment by typekpb** [comment]
@felixbarny OK, I'm convinced! thanks :)

**Comment by quintonm** [comment]
If the flag is set to disable logging of binary data, how would the user
know that the column was not null (assuming resultset data although the
same idea applied to bind parameters as well)?

**Comment by felixbarny** [comment]
I would log something like `[binary]`

**Comment by typekpb** [comment]
+1

**Comment by quintonm** [comment]
+1
