### ISSUE TITLE
Logging connection info

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [p6spy/p6spy#370]
My app connects with many different databases, and I've seen that the MessageFormattingStrategy interface provides a `connectionId`.

A `connectionId` is linked [ConnectionInformation|https://github.com/p6spy/p6spy/blob/04d3e31951ef6d630c07754ae3fb8efa570cd8c7/src/main/java/com/p6spy/engine/common/ConnectionInformation.java].
How do I have access to the name of the database and the JDBC URL?

**Comment by felixbarny** [comment]
You could try `connectionInformation.getConnection().getMetaData().getURL()`.

**Comment by DavidPerezIngeniero** [comment]
How do I get the `connectionInformation` from a `connectionId` in a `MessageFormattingStrategy` instance?

**Comment by DavidPerezIngeniero** [comment]
I answer myself: `LoggingEventListener` seems to be the clue.

**Comment by felixbarny** [comment]
That's right. You can extend `LoggingEventListener` and override `logElapsed`

**Comment by felixbarny** [comment]
Hm, that's not entirely correct as `Loggable` does not have a `getConnectionInformation` method.

@typekpb / @quintonm should we add that method?

**Comment by DavidPerezIngeniero** [comment]
Thanks Felix.  :-)

**Comment by felixbarny** [comment]
np :)

**Comment by typekpb** [comment]
> Hm, that's not entirely correct as Loggable does not have a getConnectionInformation method.
>@typekpb / @quintonm should we add that method?

@felixbarny the possible problem I see there is inheritance hierarchy, as `ConnectionInformation implements Loggable`

**Comment by felixbarny** [comment]
What about:

```java
public class ConnectionInformation implements Loggable {
    ...
    @Override
    public ConnectionInformation getConnectionInformation() {
        return this;
    }
    ...
}
```

**Comment by typekpb** [comment]
Correct, that would cover it. Should we create separate issue for this? Or
is there any volunteer for pull request, so we won't forget this?

**Comment by DavidPerezIngeniero** [comment]
Suppose this change is already made, the how can I get the `ConnectionInformation` from a custom `P6Logger` or a custom `MessageFormattingStrategy`?

**Comment by felixbarny** [comment]
You don't. You will have to override getConnectionInformation and log it yourself.

**Comment by DavidPerezIngeniero** [comment]
If I have understood well, I have to derive from `ConnectionInformation` and override `getConnectionInformation()`.
How do I register my custom implementation?

**Comment by felixbarny** [comment]
No, you have to derive from `LoggingEventListener` or `SimpleJdbcEventListener` and log the relevant information yourself using slf4j or whatever. See the Javadoc of these classes on how to register them.

**Comment by DavidPerezIngeniero** [comment]
Thanks Felix, now I'm able to trace any connection specific data.

**Comment by DavidPerezIngeniero** [comment]
Here is the code in the Scala language:

```scala
import com.p6spy.engine.common.{ConnectionInformation, PreparedStatementInformation, ResultSetInformation, StatementInformation}
import com.p6spy.engine.logging.LoggingEventListener
import com.p6spy.engine.spy.appender.MessageFormattingStrategy

object EventListener {
	case class InfoConexion(area: String, puerto: Int) {
		override def toString =
			area+(if (puerto == 5432) "" else ":"+puerto)
	}
	/** No necesita proteccion multihilo.*/
	private var registro = Map.empty[Int, InfoConexion]
	private val re = raw".*://[^:]+:(\d+)/([^/]+).*".r

	def describe(id: Int) = registro.get(id).map{_.toString}.getOrElse(s"conex $id")

	def registra(info: ConnectionInformation) {
		if (!registro.contains(info.getConnectionId)) {
			val ic = info.getConnection.getMetaData.getURL match {
				case re(puerto, baseDatos) ⇒
					InfoConexion(baseDatos, puerto.toInt)
				case _ ⇒
					InfoConexion("???", 5432)
			}
			registro += info.getConnectionId → ic
		}
	}
}

/** Captures information about connections.*/
class EventListener extends LoggingEventListener {
	import EventListener.registra
	override def onBeforeExecuteUpdate(statementInformation: StatementInformation, sql: String) = {
		registra(statementInformation.getConnectionInformation)
		super.onBeforeExecuteUpdate(statementInformation, sql)
	}

	override def onBeforeExecute(statementInformation: PreparedStatementInformation)= {
		registra(statementInformation.getConnectionInformation)
		super.onBeforeExecute(statementInformation)
	}

	override def onBeforeExecuteQuery(statementInformation: PreparedStatementInformation) = {
		registra(statementInformation.getConnectionInformation)
		super.onBeforeExecuteQuery(statementInformation)
	}

	override def onBeforeExecuteQuery(statementInformation: StatementInformation, sql: String) = {
		registra(statementInformation.getConnectionInformation)
		super.onBeforeExecuteQuery(statementInformation, sql)
	}
}

class TrazaJdbc extends MessageFormattingStrategy {
	override def formatMessage(
		connectionId: Int, now: String, elapsed: Long, category: String,
		prepared: String, sql: String) = {
		if (sql.nonEmpty) {
			val max = 400
			val sql2 = if (sql.length > max) sql.take(max)+"..." else sql
			s"${EventListener.describe(connectionId)} $sql2"
		} else ""
	}
}
```
