### ISSUE TITLE
integrate release process with travis-ci

### ISSUE THREAD

**Issue by typekpb** [p6spy/p6spy#372]
As we use travis for builds, I believe we should use it for releases as well. To prevent any magic and make releasing less painful.

**Comment by felixbarny** [comment]
How do we release right now? With Sonatype Nexus or with Bintray? I'm not sure it is possible to automate the release with Nexus. I know it is possible with Bintray. The downside is that we would have to upload the private pgp signing key to Bintray.

**Comment by typekpb** [comment]
@quintonm does the releases, so he'd know. However travis has a nice way to
encrypt stuff, so I believe it should be doable in a secure way.

**Comment by typekpb** [comment]
seems we would not be the first using travis for this, see: https://www.theguardian.com/info/developer-blog/2014/sep/16/shipping-from-github-to-maven-central-and-s3-using-travis-ci

**Comment by quintonm** [comment]
It is a bit manual right now.  The actual release is through bintray
through.  We already have the signing key added to bintray.  All that we
need is the scripting to automate the bintray side of things.

**Comment by typekpb** [comment]
with release 3.1.0 we've reached quite some automation (thanks to #377), I plan to document the release steps in our docs. Will keep it open until then

**Comment by typekpb** [comment]
sync to maven central didn't happen, despite the fact I see it in bintray: https://bintray.com/p6spy/maven/p6spy:p6spy

@felixbarny @quintonm ideas?

**Comment by felixbarny** [comment]
I have never worked with bintray. No clue, sorry.

Peter Butkovic <notifications@github.com> schrieb am Mi., 23. Aug. 2017
09:17:

**Comment by typekpb** [comment]
OK, I requested jcenter link in the bintray repo (as I had to merge repos in bintray, original one: `p6spy:p6spy` with the one I accidentally pushed to: `p6spy`). Let's see how it works out.

**Comment by typekpb** [comment]
OK, got an email from jfrog
I guess I messed it up. So what I did:

* uploaded package to `bintray/maven/p6spy` and liked it to jcenter, 
* afterwards realized it's a wrong maven repo, it should be `bintray/maven/p6spy:p6spy`
* so I merged those 2 repos, but `bintray/maven/p6spy:p6spy` doesn't show link to jcenter (as far as I can see) and making the request resulted in this email

> Hi,
> 
> The package you requested to include already exists in JCenter:
> https://bintray.com/bintray/jcenter/p6spy:p6spy
> 
> The simplest thing would be to go to the package page and make an ownership request, which will keep it linked to JCenter from your own repository:
> https://bintray.com/bintray/jcenter?filterByPkgName=p6spy:p6spy
> 
> Before you make the ownership request please make sure you remove existing versions of the package from your repo in order to prevent conflicts. This way the ownership request can go through successfully.
> 
> After the ownership request has been approved, you may deploy modules directly into your package.
> 
> Kind Regards,
> JFrog Support 


Suggestions for next steps? @quintonm I guess you've created the original repo, do you have an idea how to proceed?

**Comment by quintonm** [comment]
When you upload through the UI, it will correct the paths for you. This
might be the bst way to figure out the correct path.

For the sync to maven central, there will be a sync button displayed on the
page after you upload the files to the release. You will need to enter you
sonatype username and password there. I am guessing that part can be
automated....

**Comment by gavlyukovskiy** [comment]
I had same problem after merging two repositories in bintray, I wasn't able to link existing package in jcenter to the mine one.
@typekpb you should go to the page https://bintray.com/bintray/jcenter/p6spy%3Ap6spy and submit ownership request using `I'm the creator` button, it will ask which repository to link. Probably you would need to remove conflict versions between jcenter and bintray repositories.

**Comment by typekpb** [comment]
@gavlyukovskiy thanks for the hint!

I've tried to request ownership for:

> Ownership request for the package 'p6spy:p6spy' by:
> p6spy
> In which repository would you like to create:
> maven

but got following msg: 
> Unable to send message: A package with the name "p6spy:p6spy" already exists in the repository "maven"

**Comment by gavlyukovskiy** [comment]
Don't know what to do with that, try contact bintray support, they answer quick enough.

**Comment by typekpb** [comment]
I sent them a reply, will keep you updated.

**Comment by typekpb** [comment]
OK, new reply says:

> Hi,
> 
> In order to regain ownership of the package, remove existing packages with the same name / path prefix you have already in your private Bintray user / organization.
> 
> After performing the above, you can request a new ownership request.
> 
> We hope this clarifies more.
> 
> Regards,
> JFrog Support 

I guess I'm still a bit unsure what should be done. Should we remove the package: https://bintray.com/p6spy/maven/p6spy%3Ap6spy completely and afterwards create it again and ask for ownership? But that sounds like all the released versions would be gone. I asked them for confirmation again.

**Comment by typekpb** [comment]
OK, seems I have to remove the bintray package https://bintray.com/p6spy/maven/p6spy:p6spy and ask for ownership on https://bintray.com/bintray/jcenter/p6spy:p6spy:

> Hi,
> 
> Thank you for your reply.
> We would like to clarify about the current scenario.
> 
> Currently, there is a package named "p6spy:p6spy" which "Bintray" user has the ownership for it.
> This happens usually when a user changes the name of the package or deletes the package after it was linked to JCenter.
> 
> This behaviour is expected and it occurs to prevent changes for users who already use this package.
> The package that Bintray has ownership for (Linked to JCenter) - https://bintray.com/bintray/jcenter/p6spy:p6spy
> The new package that you created (Not linked to JCenter) - https://bintray.com/p6spy/maven/p6spy:p6spy
> 
> In order for us to regain you the ownership for the package Bintray currently has ownership to we will need you to remove the new package you have created. Please note that the content in the new package will not be saved and you > will have to deploy it again after you gain the ownership.
> 
> However, the versions that are currently in 'https://bintray.com/bintray/jcenter/p6spy:p6spy' will be saved and the package will be moved to your user.
> 
> We hope this clarifies.
> 
> Best Regards,
> JFrog Support. 

Will try to get 3.1.0 into that repo and synced to maven central afterwards. Let's see

**Comment by typekpb** [comment]
obviously I messed it up badly

**Comment by typekpb** [comment]
status update:

* dropped the repo: https://bintray.com/p6spy/maven/p6spy:p6spy via REST, as UI had restriction of up to 180 days old published artifacts on delete (was suggested by jfrog support)
* asked for ownership on: https://bintray.com/bintray/jcenter/p6spy:p6spy

**Comment by typekpb** [comment]
status update:

* bintray ownership transfered to p6spy
* 3.1.0 released to bintray
* maven central sync failed, see: #398

**Comment by typekpb** [comment]
3.2.0 release done via gradle (no manual interaction with bintray necessary any more) + release process documented via: 0a78b819e60e8cea53793a57d49200f5ee7038ae => closing
