### ISSUE TITLE
Programmatic configuration

### ISSUE THREAD

**Issue by gavlyukovskiy** [p6spy/p6spy#374]
Are there any plans/views on the programmatic configuration?

Some `JdbcEventListener` implementations may rely on the IoC container or just have dependencies that have to be created from outside a listener/factory e.g. https://github.com/openzipkin/brave/blob/master/brave-p6spy/src/main/java/com/github/kristofa/brave/p6spy/BraveP6SpyListener.java
Does it make sense to implement dynamic non-reflective registration of listeners (or make public method to register modules and maybe keep user registered modules on reload).
As I understtod `P6ModuleManager.getInstance().getFactories().add(...)` is not really correct approach.

Also it would be great to have ability to register own `P6OptionsSource` implementations.

**Comment by typekpb** [comment]
well, what we currently support is using [service loader](http://docs.oracle.com/javase/6/docs/api/java/util/ServiceLoader.html) mechanism, but maybe dynamic way could make sense as well.

@felixbarny @quintonm ideas?

**Comment by gavlyukovskiy** [comment]
I asked for it because I wanted to create own listeners and use them depending on spring context, my application uses spring-boot so I can use its context to declare P6Facroty as a bean and somehow inject it into P6Spy at runtime.
Ideally I want to write listener to keep metrics like transactions count per X, transaction duration percentiles and these metrics should be stored using spring context beans - dao, repositories. But I can not control process of creation of `P6Factory` and only one way to inject these beans into my metrics listener factory as soon as posible (and handle in listener initial sql requests untill dependencies are injected).

Idea was to create custom spring-boot-starter that will do the magic of adding factories to the `P6ModuleManager`, I tried to use P6Factory beans and reflectievly call `registerModule(P6Factory)`, but I want to have something more convinient.

On the other hand I don't really need to access `P6LoadableOptions` because I can configure my listener directly using spring context, thus `P6Factory` not required as well. I decided to register single `RuntimeListenerSupportFactory` that will return compound listener of all listener beans defined in the context.

Using my starter all `JdbcEventListener` defined in the context is applied though `RuntimeListenerSupportFactory`. Maybe you can suggest what problems I may face with this approach? 

P.S. my starter code: https://github.com/gavlyukovskiy/spring-boot-data-source-decorator/tree/master/datasource-decorator-spring-boot-autoconfigure/src/main/java/com/github/gavlyukovskiy/boot/jdbc/decorator/p6spy

**Comment by felixbarny** [comment]
Being able to add listeners at runtime makes a lot of sense. If you want, please create a pr.

> Ideally I want to write listener to keep metrics like transactions count per X, transaction duration percentiles and these metrics should be stored using spring context beans - dao, repositories. 

That sounds like something stagemonitor does already. It is built on top of p6spy. Disclaimer: I'm the author of stagemonitor.

In this post, I've attached a picture of the corresponding grafana dashboard: https://github.com/stagemonitor/stagemonitor-mailinglist/issues/46. Note that you can select `jdbc` in the `Operation Type` filter.

**Comment by gavlyukovskiy** [comment]
I'm not such familiar with P6Spy code to push a pull request... In my case all is much easier - I register `RuntimeListenerSupportFactory` only if listeners were found in the spring context and at the moment of initializing `P6ModuleManager` my factory abble to retrieve them and no one will change listeners at real runtime (after spring context is initialized). 

Depending on how it could affect P6Spy when listener was added in the middle of sql transaction I can return compound listener from some static listener storage, I'm not sure all will be fine.

I was looking for something like stagemonitor, thanks. I'll try to play with it.

**Comment by typekpb** [comment]
closed by #400
