### ISSUE TITLE
Event on closing statement

### ISSUE THREAD

**Issue by gavlyukovskiy** [p6spy/p6spy#376]
I'm trying to track count of active statements but I didn't find an event after Statement / PreparedStatement / CallableStatement is closed.
Does it makes sence to add `onAfterStatementClose`?

**Comment by typekpb** [comment]
@gavlyukovskiy thanks for report. Sounds like a good idea to me.

@felixbarny @quintonm The questoin is if we also want to log it. If so, we should probably recycle `excludecategory=statement` here, to enable filtering and log something in a sense:

     ... | statement | close | 

moreover it seems we should keep this in sync with other `Closeable` implementations and log similar onse for:

     ... | resultset | close | 
     ... | connection | close | 

considering respective `excludecategory` as well.

Ideas?

**Comment by felixbarny** [comment]
Sounds good

**Comment by typekpb** [comment]
well, logging part has not been requested by the issue reporter and we didn't support it for existing on*Close() events, so maybe let's keep it out, unless someone explicitly asks for it

**Comment by gavlyukovskiy** [comment]
Thanks for the fast reaction. Also you have event `onConnectionWrapped` and it does not cover, for my opinion, important case when exception has been thrown on getting connection (db issues or data source connection timeout). 
It may be useful for building own metrics to have along with acquire time to get connection also count of actually failed to acquire connections. WDYT?

**Comment by typekpb** [comment]
@gavlyukovskiy please keep the issues separated (makes future references easier) => raise new one, if needed
