### ISSUE TITLE
Add event onBeforeConnectionGet and/or onAfterConnectionGet

### ISSUE THREAD

**Issue by gavlyukovskiy** [p6spy/p6spy#381]
JdbcEventListener has various events for tracking abnormally behavior such like `SQLException`'s while executing query or processing `ResultSet`.
Currently there is only lack in tracking getting `Connection` issues, such may happen either when issue on db side or datasource is configured to throw `SQLException` after timeout on acquiring connection.

**Comment by felixbarny** [comment]
A `onAfterGetConnection` Method would be a nice addition. However, it would require some refactoring since the `JdbcEventListener`s are only instantiated when the `Connection` is successfully obtained.

**Comment by gavlyukovskiy** [comment]
So as I understtod you don't want to instantiate filters if getting connection may be failed?

**Comment by felixbarny** [comment]
With filters you mean event listeners? No, I just stated that they are currently only instantiated/invoked when getConnection succeeds. This has to be changed so that they get invoked on failure. See also P6Core.

**Comment by gavlyukovskiy** [comment]
Oh, sorry, listeners. If the listener will be created in both cases we can initialize listeners once `P6DataSource.getConnection()` is called and implement `onBeforeConnectionGet(DataSource)` as well, right? It's not needed in my case, but some pools may not have timeout on `getConnection()`.

**Comment by felixbarny** [comment]
One thing to bear in mind is that not only `DataSource`s create `Connection`s but also `Diver`s and `PooledConnection`s. I'm not sure why you would need an `onBeforeGetConnection` callback. What could it be used for?

I'd probably add a `onAfterGetConnection(ConnectionInformation, SQLException)` method:

```java
public abstract class JdbcEventListener {
  /**
   * ...
   * connectionInformation.connection is null when SQLException is not null
   * ...
   */
  public void onAfterGetConnection(ConnectionInformation connectionInformation, SQLException e) {
  }

  /**
   * @deprecated Use {@link #onAfterGetConnection(ConnectionInformation, SQLException)}
   */
  @Deprecated
  public void onConnectionWrapped(ConnectionInformation connectionInformation) {
  }
}
```

Also, I'd add `P6Core#getJdbcEventListener` which can be called from `P6DataSource`, `P6PooledConnection` and `P6SpyDriver` to call `JdbcEventListener#onConnectionWrapped` (after real  call to `getConnection`) and `JdbcEventListener#onAfterGetConnection` (in finally block).

**Comment by gavlyukovskiy** [comment]
Sounds good
