### ISSUE TITLE
IronTrack

### ISSUE THREAD

**Issue by bardware** [p6spy/p6spy#382]
Hi,

according to what I read on the internet, in the past there was a tool `IronTrack` that would visualize the output of p6spy in a JAVA GUI.
An [instruction](http://jdbforms.sourceforge.net/UsersGuide/html/ch27s10.html) says to modify `module.monitor` directive. This line is not present in the samply `spy.properties` in your `3.0.0` release  download.

Do you have an idea if it's possible to get the GUI working with your recent release or if there's a GUI for your tool?

**Comment by typekpb** [comment]
well, the link you provided seems to be outdated, any chance for more recent irontrack docs?

**Comment by quintonm** [comment]
You should still be able to use IronEye with P6Spy 1.3. Unfortunately,
IronEye is a dead product now. If you can find the source code anywhere,
you should be able to update it to use P6Spy 3.x.

BTE- I think that module.monitor was actually a IronEye directive. This was
likely a custom P6Spy module that was included with the product.

**Comment by typekpb** [comment]
closing, feel free to reopen if necessary
