### ISSUE TITLE
CsvReporter should set separator in dependence of locale-dependent decimal separator

### ISSUE THREAD

**Issue by siom79** [p6spy/p6spy#390]
Using the CsvReport for example with a German locale, results in a CSV file that uses the comma as separator between the columns but additionally also as decimal separator:
```
1502448484,100,1,081546,0,610664,0,441010,0,097851,0,596013,0,643630,0,794799,0,971580,1,080447,1,081546,11,095617,0,090692,24,310302,69,889724,calls/minute,milliseconds
```
In the line above it is not clear where each column starts.

As the JDK class [DecimalFormatSymbols](http://docs.oracle.com/javase/6/docs/api/java/text/DecimalFormatSymbols.html) provides the decimal separator derived from the given locale, it should be possible to use a different char for the column separator. 

In general it would be useful to be able to provide the separator char for columns as parameter to the CsvReport builder.

**Comment by typekpb** [comment]
@siom79 I don't know the class CsvReport, could you provide more info on that?

**Comment by siom79** [comment]
Sorry, wrong project. :confused:

**Comment by typekpb** [comment]
Ok, no problem
