### ISSUE TITLE
ClassNotFoundException: com.p6spy.engine.spy.appender.CustomLineFormat

### ISSUE THREAD

**Issue by ztkmkoo** [p6spy/p6spy#396]
Hi~

I need some help with p6spy:3.0.0.

in configuration manual, it says
`com.p6spy.engine.spy.appender.CustomLineFormat, which allows log messages to be full customized, in a separate property called customLogMessageFormat. See below for details.`

in my gradle project which dependencies: p6spy:p6spy:3.0.0
there is no customlineformat class in the library.
and its the sc below.
![image](https://user-images.githubusercontent.com/26991409/29853397-b20179be-8d7a-11e7-841a-1c265eafd82c.png)

and Finally throw the errors below. check it.
```
Cannot instantiate com.p6spy.engine.spy.appender.CustomLineFormat, even on second attempt. 
java.lang.ClassNotFoundException: com.p6spy.engine.spy.appender.CustomLineFormat
```

**Comment by ztkmkoo** [comment]
Do i have to create a class/or interface implements MessageFormattingStrategy

and,
set logMessageFormat=com.p6spy.engine.spy.appender.CustomLineFormat -> com.myproject.CustomLineFormat??

**Comment by typekpb** [comment]
@ztkmkoo the feature you're refering to is not yet present in any released version of p6spy. So either wait for the next official release (after 3.1.0, as we currently have trouble with releasing that to maven central, see: #372), or use the latest snapshot (3.1.1-SNAPSHOT version) from repo: http://oss.jfrog.org/oss-snapshot-local/p6spy/p6spy/3.1.1-SNAPSHOT/

**Comment by ztkmkoo** [comment]
thx
