### ISSUE TITLE
3.2.0 version release

### ISSUE THREAD

**Issue by typekpb** [p6spy/p6spy#399]
as we have new feature #391 I suggest to go for 3.2.0 version (http://semver.org/), once we have #398 merged.

However 3.1.0 didn't make it to maven central, but well, users care about latest only, I guess.

Pending:

- [X] #398 merged
- [X] release notes - 3.2.0 updates
- [X] release notes - document 3.1.0 in bintray only (no maven central)

**Comment by jorgheymans** [comment]
:+1: for 3.2.0 then

**Comment by gavlyukovskiy** [comment]
any chance to get https://github.com/p6spy/p6spy/pull/384 in the 3.2.0?

**Comment by typekpb** [comment]
@gavlyukovskiy  well, if @felixbarny won't make a review, I guess, I can

**Comment by felixbarny** [comment]
That would be really nice. I'm sorry that I can't contribute as much at the moment.

**Comment by typekpb** [comment]
no problem, will do

**Comment by typekpb** [comment]
I was too inpatient with 3.2.0 release, seems new process is finally working: https://api.travis-ci.org/jobs/270775833/log.txt?deansi=true

bintray maven sync seems to work ok as well:
>Sync Status
>Last Synced:
>   Fri Sep 01 10:48:13 GMT 2017
> Last Sync Status:
>  Successfully synced and closed repo.
> Last Sync Errors:
>     N/A 

@gavlyukovskiy we'll include your changes in next one (3.3.0, I guess), as soon as we can review it, but with new process, release seems to be super-easy, so I hope for the higher frequency
