### ISSUE TITLE
No visible constructors in class com.p6spy.engine.wrapper.ConnectionWrapper

### ISSUE THREAD

**Issue by Worsik** [p6spy/p6spy#401]
I am upgrading P6SPY on our Java applications based on Spring framework. Current p6spy version is 2.1.4 and we want at least version 3.0.0 (or 3.2.0).

We have Aspect class, which is around execution of `javax.sql.DataSource.getConnection(..)`. This class allouws us to set client identifier to DB session and on connection close, clear identifier again.
Class is not depending on p6spy or other library and is in shared code library. Our applications use p6spy for SQL logging and we want to use new features like excludebinary.

After I changed version in pom.xml and deployed application, some AOP errors appeared in our Aspect class.

> ERROR mypackage.db.aspect.ClientIdentifierAspect-
> org.springframework.aop.framework.AopConfigException: Could not generate CGLIB subclass of class [class com.p6spy.engine.wrapper.ConnectionWrapper]: Common causes of this problem include using a final class or a non-visible class; nested exception is java.lang.IllegalArgumentException: No visible constructors in class com.p6spy.engine.wrapper.ConnectionWrapper
>     at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:212) ~[spring-aop-4.2.1.RELEASE.jar:?]
>     at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:109) ~[spring-aop-4.2.1.RELEASE.jar:?]
>     at mypackage.db.aspect.ClientIdentifierAspect.onNewConnection(ClientIdentifierAspect.java:61) [orionutil-db-2.34-SNAPSHOT.jar:?]
> ...
> Caused by: java.lang.IllegalArgumentException: No visible constructors in class com.p6spy.engine.wrapper.ConnectionWrapper
>     at org.springframework.cglib.proxy.Enhancer.filterConstructors(Enhancer.java:531) ~[spring-core-4.2.1.RELEASE.jar:?]
>     at org.springframework.cglib.proxy.Enhancer.generateClass(Enhancer.java:448) ~[spring-core-4.2.1.RELEASE.jar:?]
>     at org.springframework.cglib.transform.TransformingClassGenerator.generateClass(TransformingClassGenerator.java:33) ~[spring-core-4.2.1.RELEASE.jar:?]
>     at org.springframework.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25) ~[spring-core-4.2.1.RELEASE.jar:4.2.1.RELEASE]
>     at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:216) ~[spring-core-4.2.1.RELEASE.jar:4.2.1.RELEASE]
>     at org.springframework.cglib.proxy.Enhancer.createHelper(Enhancer.java:377) ~[spring-core-4.2.1.RELEASE.jar:?]
>     at org.springframework.cglib.proxy.Enhancer.createClass(Enhancer.java:317) ~[spring-core-4.2.1.RELEASE.jar:?]
>     at org.springframework.aop.framework.ObjenesisCglibAopProxy.createProxyClassAndInstance(ObjenesisCglibAopProxy.java:55) ~[spring-aop-4.2.1.RELEASE.jar:?]
>     at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:202) ~[spring-aop-4.2.1.RELEASE.jar:?]
> 

In older version of p6spy this problem didn't exist. Is there a way how to allow this functionality witjout workarounds?

Our current solution is to check whether connection is wrapped by p6spy ConnectionWrapper an in that case unwrap, add advice by proxy factory and wrap connection again. It makes our shared code dependent on p6spy library which needs to be added to our shared code pom.xml.
And in that solution not everything is perfect. For example call of SQL clearing the identifier from DB session is not logged by p6spy.

**_Code before workaround:_**
```
package mypackage.db.aspect;

import mypackage.db.security.SecurityHolder;
import java.lang.reflect.Method;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import org.aspectj.lang.ProceedingJoinPoint;
import org.aspectj.lang.annotation.Around;
import org.aspectj.lang.annotation.Aspect;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.aop.MethodBeforeAdvice;
import org.springframework.aop.aspectj.AspectJExpressionPointcutAdvisor;
import org.springframework.aop.framework.ProxyFactory;
import org.springframework.stereotype.Component;

@Component
@Aspect
public class ClientIdentifierAspect {

    private static Logger log = LoggerFactory.getLogger(ClientIdentifierAspect.class);

    @Around("execution(* javax.sql.DataSource.getConnection(..))")
    public Connection onNewConnection(final ProceedingJoinPoint pjp) throws Throwable {
        Connection connection = (Connection) pjp.proceed(pjp.getArgs());
        if (connection != null) {
            String loginName = SecurityHolder.getOwner() != null ? SecurityHolder.getOwner().getLoginName() : "";
            //loginName = loginName.replaceAll("'", "''");
            try (CallableStatement cs = connection.prepareCall("{ call DBMS_SESSION.SET_IDENTIFIER(?) }")) {
                cs.setString(1, loginName);
                cs.execute();

                // proxy trida pro smazani identifieru pri uzavirani spojeni
                // viz https://beautifulbytes.wordpress.com/2013/01/21/use-spring-aop-and-jmx-to-monitor-and-cancel-jdbc-statements/
                ProxyFactory factory = new ProxyFactory();
                factory.setProxyTargetClass(true);
                factory.setTarget(connection);
                AspectJExpressionPointcutAdvisor aspectJExpressionPointcutAdvisor = new AspectJExpressionPointcutAdvisor();
                aspectJExpressionPointcutAdvisor.setExpression("execution (* java.sql.Connection.close(..))");
                aspectJExpressionPointcutAdvisor.setAdvice(new MethodBeforeAdvice() {
                    @Override
                    public void before(Method method, Object[] args, Object target) throws Throwable {
                        Connection con = (Connection) target;
                        try (CallableStatement cs = con.prepareCall("{ call DBMS_SESSION.CLEAR_IDENTIFIER() }")) {
                            cs.execute();
                        } catch (SQLException ex) {
                            throw ex;
                        }
                    }
                }
                );
                factory.addAdvisor(aspectJExpressionPointcutAdvisor);
                ClassLoader contextClassLoader = Thread.currentThread().getContextClassLoader();
                connection = (Connection) factory.getProxy(contextClassLoader);
            } catch (SQLException ex) {
                throw ex;
            } catch (Exception ex) {
                log.error("", ex);
            }
        }
        return connection;
    }
}

```
**_Code after workaround:_**
```
package mypackage.db.aspect;

import com.p6spy.engine.common.ConnectionInformation;
import com.p6spy.engine.spy.P6Core;
import com.p6spy.engine.wrapper.ConnectionWrapper;
import mypackage.db.security.SecurityHolder;
import java.lang.reflect.Method;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import org.aspectj.lang.ProceedingJoinPoint;
import org.aspectj.lang.annotation.Around;
import org.aspectj.lang.annotation.Aspect;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.aop.MethodBeforeAdvice;
import org.springframework.aop.aspectj.AspectJExpressionPointcutAdvisor;
import org.springframework.aop.framework.ProxyFactory;
import org.springframework.stereotype.Component;

@Component
@Aspect
public class ClientIdentifierAspect {

    private static Logger log = LoggerFactory.getLogger(ClientIdentifierAspect.class);

    @Around("execution(* javax.sql.DataSource.getConnection(..))")
    public Connection onNewConnection(final ProceedingJoinPoint pjp) throws Throwable {
        Connection connection = (Connection) pjp.proceed(pjp.getArgs());
        if (connection != null) {
            String loginName = SecurityHolder.getOwner() != null ? SecurityHolder.getOwner().getLoginName() : "";
            //loginName = loginName.replaceAll("'", "''");
            try (CallableStatement cs = connection.prepareCall("{ call DBMS_SESSION.SET_IDENTIFIER(?) }")) {
                cs.setString(1, loginName);
                cs.execute();

                AspectJExpressionPointcutAdvisor aspectJExpressionPointcutAdvisor = new AspectJExpressionPointcutAdvisor();
                aspectJExpressionPointcutAdvisor.setExpression("execution (* java.sql.Connection.close(..))");
                aspectJExpressionPointcutAdvisor.setAdvice(new MethodBeforeAdvice() {
                    @Override
                    public void before(Method method, Object[] args, Object target) throws Throwable {
                        Connection con = (Connection) target;
                        try (CallableStatement cs = con.prepareCall("{ call DBMS_SESSION.CLEAR_IDENTIFIER() }")) {
                            log.info("p6spy\n{ call DBMS_SESSION.CLEAR_IDENTIFIER() }");    // need of log out of p6spy
                            cs.execute();
                        } catch (SQLException ex) {
                            throw ex;
                        }
                    }
                });
                // proxy trida pro smazani identifieru pri uzavirani spojeni
                // viz https://beautifulbytes.wordpress.com/2013/01/21/use-spring-aop-and-jmx-to-monitor-and-cancel-jdbc-statements/
                ProxyFactory factory = new ProxyFactory();
                boolean wrapBack = false;
                ConnectionInformation ci = null;
                if (connection instanceof ConnectionWrapper) {
                    ConnectionWrapper w = (ConnectionWrapper) connection;
                    ci = w.getConnectionInformation();
                    Connection unwrap = (Connection) w.unwrapP6SpyProxy();
                    factory.setProxyTargetClass(false);
                    factory.setTarget(unwrap);
                    wrapBack = true;
                } else {
                    factory.setProxyTargetClass(true);
                    factory.setTarget(connection);
                }
                ClassLoader contextClassLoader = Thread.currentThread().getContextClassLoader();
                factory.addAdvisor(aspectJExpressionPointcutAdvisor);
                connection = (Connection) factory.getProxy(contextClassLoader);
                if (wrapBack && ci != null) {
                    connection = P6Core.wrapConnection(connection, ci);
                }

            } catch (SQLException ex) {
                throw ex;
            } catch (Exception ex) {
                log.error("", ex);
            }
        }
        return connection;
    }
}
```

[My question on stackowerflow](https://stackoverflow.com/questions/46035251/p6spy-3-x-configuration-avoid-no-visible-constructors-in-class-com-p6spy-engine/46070089#46070089)

**Comment by typekpb** [comment]
@Worsik well, couple minutes ago I made a pull request #400, that would provide public constructor for ConnectorWrapper. So if you can wait for it to get merged (could theoretically make it to 3.3.0 version), your trouble should be over.

**Comment by Worsik** [comment]
@typekpb Thank you for information, for now we can live with actual workaround but I'll create an issue in our JIRA for upgrade to 3.3.0 ASAP and will see if problem is solved after upgrade

**Comment by typekpb** [comment]
Excelent

On Sep 6, 2017 11:54, "Worsik" <notifications@github.com> wrote:

@typekpb <https://github.com/typekpb> Thank you for information, for now we
can live with actual workaround but I'll create an issue in our JIRA for
upgrade to 3.3.0 ASAP and will see if problem is solved after upgrade

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/p6spy/p6spy/issues/401#issuecomment-327435294>, or mute
the thread

**Comment by typekpb** [comment]
@Worsik 3.3.0 version holding a fix has been just releaseed would you mind giving it a try and providing us with the feedback (sync to maven central might take 1 day or so)?

**Comment by Worsik** [comment]
I've just tried to reproduce problem on our code without workaround with only changing version to 3.3.0. Everything seems to be fine, no errors at all.

Thank you, I'm closing this issue right now

**Comment by typekpb** [comment]
Excelent, thanks!
