### ISSUE TITLE
Parameter replacement in hibernate prepared statements

### ISSUE THREAD

**Issue by Worsik** [p6spy/p6spy#402]
I was turning on p6spy in one of our applications and I am wondering, why p6spy doesn't replace ordinal nor named query parameters. Only parameters which are replaced by their value are those written as question mark.

I took a look in code of [PreparedStatementInformation](https://github.com/p6spy/p6spy/blob/master/src/main/java/com/p6spy/engine/common/PreparedStatementInformation.java#L45) class to be sure about it.
```
public String getSqlWithValues() {
    final StringBuilder sb = new StringBuilder();
    final String statementQuery = getStatementQuery();

    // iterate over the characters in the query replacing the parameter placeholders
    // with the actual values
    int currentParameter = 0;
    for( int pos = 0; pos < statementQuery.length(); pos ++) {
      char character = statementQuery.charAt(pos);
      if( statementQuery.charAt(pos) == '?' && currentParameter <= parameterValues.size()) {
        // replace with parameter value
        Value value = parameterValues.get(currentParameter);
        sb.append(value != null ? value.toString() : new Value().toString());
        currentParameter++;
      } else {
        sb.append(character);
      }
    }

    return sb.toString();
  }
```

[Hibernate specifies](http://www.objectdb.com/java/jpa/query/parameter) two options: named (`:name`) or ordinal parameters (`?index`).
Is there a way to support these placeholders?
It is still possible to use only question mark, but it would be great to support named / ordinal parameters. Otherwise developer needs to do a lot of refactoring when starting to use p6spy, if we wants to see parameter values in log entry.

**Comment by typekpb** [comment]
@Worsik nice catch!

**Comment by gavlyukovskiy** [comment]
Doesn't Hibernate replace named and ordinal parameters to a `?` before create prepared statement? For example named parameters in `NamedParameterJdbcTemplate` from spring are replaced with `?` before calling `prepareStatement`, as p6spy works on a jdbc level hibernate parameters should be resolved as well.

For example here is an sql tag created using `getSqlWithValues`: https://github.com/gavlyukovskiy/spring-boot-data-source-decorator/blob/master/images/query-span.png
as you can see all parameters are visible in sql.

**Comment by typekpb** [comment]
well, sounds like a closing candidate, @Worsik feel free to close, unless there are any further actions required

**Comment by Worsik** [comment]
Sorry for pending, I'm closing issue and will try  your suggestions later. For now it is not on the ASAP list :-)
