### ISSUE TITLE
NPE in SimpleJdbcEventListener implementation

### ISSUE THREAD

**Issue by jorgheymans** [p6spy/p6spy#407]
Hi,

Since 3.3.0 i am getting NPE in https://github.com/openzipkin/brave/blob/f419332ac0532ed6a2996140397e16457dd58e5c/instrumentation/p6spy/src/main/java/brave/p6spy/TracingJdbcEventListener.java#L61 . 

It seems to indicate that onAfterAnyExecute is getting called without a corresponding onBeforeAnyExecute? Was there ever any guarantee that onBefore/onAfter were always going to be called in pair ?

Jorg

**Comment by jorgheymans** [comment]
@adriancole FYI

**Comment by typekpb** [comment]
@jorgheymans any chance for full stacktrace? it could help in analysis, I guess

**Comment by typekpb** [comment]
there seems to be some conditional statements in the `TracingJdbcEventListener` before the actual call. So what could be done, to make sure, is to log the call of the method as the first statement with some unique id held in thread-local => before/after executions could be pared.

**Comment by jorgheymans** [comment]
@typekpb we are going to do exactly this, for now an extra null check solved the problem. 

My question was also more about the semantics of p6spy, i.e. is it possible for an onAfterExecute to be called without a corresponding onBefore first, or should this never happen ?

**Comment by felixbarny** [comment]
This should never happen. If it does, it's a bug.

**Comment by jorgheymans** [comment]
ok understood !
