### ISSUE TITLE
Don't hex encode value (byte) if it's really a printable string

### ISSUE THREAD

**Issue by jonespm** [p6spy/p6spy#409]
I love using p6spy but for some reason almost everything in our logs is converted to hex encoded, this makes using the output really cumbersome.

For example
`1506525969459|1|statement|connection 0|select SITE_ID from SAKAI_SITE where ( SITE_ID = ? )|select SITE_ID from SAKAI_SITE where ( SITE_ID = '36353537666162382D656165382D346536652D393665632D653030613335653136306465' )`

Where this should say
`1506525969459|1|statement|connection 0|select SITE_ID from SAKAI_SITE where ( SITE_ID = ? )|select SITE_ID from SAKAI_SITE where ( SITE_ID = '6557fab8-eae8-4e6e-96ec-e00a35e160de' )`

The database is mysql and the column type for this is varchar(99). I'm not entirely sure how it's determining that it's binary. I see in Value.java (convertToString) it has a special case for Date (which we do override), and if it's a byte[] it either prints **[binary]** or hex encodes. I think it would be minimally nice to see if it was ASCII/printable and print that. I have a PR for what has made this a work a lot better for us. Maybe there's a better solution.

Thanks!

**Comment by felixbarny** [comment]
How do you set the uuid in the PreparedStatement? Are you using plain JDBC or JPA? Could you paste the code how you construct the select?

**Comment by felixbarny** [comment]
You probably provide the UUID as a java.util.UUID instance and don't call `.toString()` on it. It seems like sakai calls `toString()` on unknown types but then calls `setByte`:

https://github.com/sakaiproject/sakai/blob/5c99c3a3e431abf1693ef5bb6dfff1fe4dea3fc9/kernel/kernel-impl/src/main/java/org/sakaiproject/db/impl/BasicSqlService.java#L2248

**Comment by felixbarny** [comment]
I'm not sure if we should detect if the provided byte[] might be a String. IMHO that's a wrong use of the JDBC API. I'm not sure if sakai handles that correctly. It seems quite "dangerous" to just call `toString`, set this as a byte[] and hope for the best. I'd suggest calling `toString` on `java.util.UUID` instances before setting them as prepared statement arguments.

**Comment by jonespm** [comment]
Thanks @felixbarny. It looks like changing adding an instanceof String in this method fixes the p6spy output. This is code that hasn't been touched in ages. We'd like to migrate out of this custom class but just haven't refactored it yet. I'd agree about toString->byte and hoping it works isn't great. It looks like that's what was happening though.

**Comment by jonespm** [comment]
I think this can be closed, thanks for looking at it.
