### ISSUE TITLE
Consider adding onBeforeConnectionGet

### ISSUE THREAD

**Issue by gavlyukovskiy** [p6spy/p6spy#411]
Hi, some time ago I asked to add event `onAfterConnectionGet` to make exception logging possible - https://github.com/p6spy/p6spy/issues/381, there I've also asked to add `onBeforeConnectionGet` but with no real reasons to do so. I played a bit with new event and I have couple of cases where `onBeforeConnectionGet` would be useful.
1. Visualization (e.g. Zipkin): 
  I have connection pool with 5 connections and acquisition timeout set to 5s. Imagine I have demand for 10 connections with 7s transaction time each. If acquiring of 5 connections failed with pool timeout, I will not be able to retroactively create a span, but only create a span just after connection had been acquired (or failed to acquire) which will be displayed incorrectly - without connection wait time:
![2017-09-29](https://user-images.githubusercontent.com/15277543/30993510-0cad5366-a4b8-11e7-94f4-e0988392ff78.png)
but actually should look different, because I tried to acquire 10 connection at the same time, but 5 of them failed after 5s timeout:
![2017-09-29 1](https://user-images.githubusercontent.com/15277543/30993544-26d3b2d0-a4b8-11e7-8bac-b6fa05a4a133.png)
2. Metrics
  Inspired by HikariCP metrics integration I want to know how many connections are pending acquisition. Having `onBeforeConnectionGet` would give me ability to create counter that is incremented before getting a connection and decremented after.

Just like the previous issue I am willing to implement this one as well. 
At first sight changes are minimal now - adding more factory methods to `ConnectionInformation` without a `Connection` and `timeToGetConnectionNs` that won't be available at the moment of calling `onBeforeConnectionGet`, adding appropriate getters for these fields and creating `ConnectionInformation` little bit earlier in the flow.

What do you think?

**Comment by felixbarny** [comment]
Sounds good.

Theres one thing I don't quite understand. In your first example, when you know the timeToGetConnectionNs, why can't you retrospectively create a span?

**Comment by gavlyukovskiy** [comment]
Span creation is not under my control in sleuth (library that integrates zipkin with spring cloud/boot). `Tracer#createSpan` does not allow to set timestamp, I'm not sure if I can use `Tracer#continueSpan`.

**Comment by felixbarny** [comment]
I see. Out of curiosity, are there plans to migrate to OpenTracing in sleuth?

**Comment by gavlyukovskiy** [comment]
I'm not an active Sleuth contributor, most probably you already found discussion about OpenTracing integration, just if you don't: https://github.com/spring-cloud/spring-cloud-sleuth/issues/599

**Comment by marcingrzejszczak** [comment]
Starting with `2.0.0.M6`, Sleuth will be OpenTracing compatible (https://github.com/spring-cloud/spring-cloud-sleuth/commit/22d91bac247e8273fa93ffe05f50179182425f72). @gavlyukovskiy I remember you had a py6spy - Sleuth integration somewhere. Remember to try to align with the latest `2.0.0` changes. We've fully migrated to Brave https://github.com/spring-cloud/spring-cloud-sleuth/issues/711
