### ISSUE TITLE
3.4.0 release

### ISSUE THREAD

**Issue by typekpb** [p6spy/p6spy#413]
I guess it's time.
Any volunteer?

**Comment by typekpb** [comment]
ok, pressure came from the comment in: #405 
I'm volunteering for the release :)

**Comment by felixbarny** [comment]
ty

**Comment by anandvarkeyphilips** [comment]
Hi, I am also waiting for Java 6 compatibility.. When is the release?? :)

**Comment by typekpb** [comment]
well, there seems to be some problem with our travis build right now (fails), I'm working on it, let's see

**Comment by typekpb** [comment]
@anandvarkeyphilips well, your last comment in #405 put some pressure on the issue, so release has been done just a moment ago. If you're patient enough, java 6 compatible version should be in maven central tomorrow for you. Or if you don't need maven repo, go for jar in the bintray: https://bintray.com/p6spy/maven/p6spy%3Ap6spy/3.4.0#files/p6spy%2Fp6spy%2F3.4.0

And finally, p6spy 3.4.0 is the version you should be interested in (bringing back the java 6 compatibility).

**Comment by typekpb** [comment]
release done, closing
