### ISSUE TITLE
Document which APIs are public and which are internal

### ISSUE THREAD

**Issue by typekpb** [p6spy/p6spy#422]
we should find a proper way to document public API
Need raised in: #420 as well as #418 

ideas welcome

**Comment by felixbarny** [comment]
Proposal

Public:
- `common` only these classes:
  - PreparedStatementInformation
  - ResultSetInformation
  - StatementInformation
  - CallableStatementInformation
  - ConnectionInformation
- `event`
- `wrapper`
- `spy`

Internal:
- `logging`
- `outage`


Discuss:
- `spy` not quite sure about this one. At least these classes have to be public:
  - P6Core
  - P6XAConnection
  - P6SpyDriver
  - P6DataSource
  - P6PooledConnection

We could document and enforce this va `module-info.java`

**Comment by typekpb** [comment]
@felixbarny I agree with proposed list.

PR welcome

do you think we should wait with 3.5.0 release for this one?

**Comment by felixbarny** [comment]
What do you think about the other classes in the `spy` package?

> do you think we should wait with 3.5.0 release for this one?

I think we can do this after 3.5.0

**Comment by typekpb** [comment]
@felixbarny well, I guess your list is complete. Anyway, if people see the need for including additional classes to public API it should be just a question of common agreement. However changing public API to private one sounds like a bad idea.
So being restrictive sounds like a good approach to me.

**Comment by felixbarny** [comment]
brave-p6spy also uses `P6LoadableOptions`. Probably `P6Factory` should be public as well as it's used by brave-p6spy. This class also has a dependency on `com.p6spy.engine.spy.option`. Now the dependencies get a bit weird. `com.p6spy.engine.spy.option.P6OptionsRepository` depends on `com.p6spy.engine.logging.Category` which does not belong to the public API.

**Comment by typekpb** [comment]
Well, sounds like we should make Category a part of public API as well to
move this forward.

**Comment by typekpb** [comment]
no volunteers for the fix => closing
