### ISSUE TITLE
Make the format for boolean parameters configurable

### ISSUE THREAD

**Issue by OBreidenbach** [p6spy/p6spy#426]
I would be nice, if it was possible to log boolean parameters as '0' and '1' and not as 'false' and 'true'.
PR will follow.

**Comment by OBreidenbach** [comment]
PR: https://github.com/p6spy/p6spy/pull/427

**Comment by typekpb** [comment]
docs updates pending (http://p6spy.readthedocs.io/en/latest/configandusage.html), will close once it's done

**Comment by typekpb** [comment]
docs fixed => closing
