### ISSUE TITLE
Old documentation at https://p6spy.github.io/p6spy?

### ISSUE THREAD

**Issue by OBreidenbach** [p6spy/p6spy#428]
Searching for the documentation, Google gives me 'https://p6spy.github.io/p6spy' as first result. This is confusing, it seems to be outdated.
May be there could be added a note and/or a link referring to the current documentation at http://p6spy.readthedocs.io.
Even better would be to remove this old documentation or just redirect to the current documentation.

**Comment by anandvarkeyphilips** [comment]
I also felt the same!! :)

**Comment by typekpb** [comment]
Redirecting sounds like the right approach. PRs welcome. Fix would be merged to gh-pages afterwards.

**Comment by typekpb** [comment]
@OBreidenbach seems you did some work in the area, any plans for creating a pull request, so the discussion can be initiated?

**Comment by OBreidenbach** [comment]
PR #432, replaces the old documentation by a redirect.
