### ISSUE TITLE
Duplicate sql batch entries 

### ISSUE THREAD

**Issue by rmahnovetsky** [p6spy/p6spy#430]
I noticed when batch entries are added the same sql is logged twice, once on batch add and once on execution, see LoggingEventListener code below. Is it possible to change the category of one of those entries? e.g. Category.ADD_BATCH

In my case I did a work around and followed the instruction at the top of the LoggingEventListener and created a custom implementation so onAfterExecuteBatch did nothing.

I needed to do this because I'm using p6spy in my tests to count the number of sql calls being made. When batch category is enabled I'm getting duplicates and I have no easy way to filter or exclude the duplicates out. 

LoggingEventListener

```
@Override
  public void onAfterExecuteBatch(StatementInformation statementInformation, long timeElapsedNanos, int[] updateCounts, SQLException e) {
    logElapsed(statementInformation, timeElapsedNanos, Category.BATCH, e);
  }
  @Override
  public void onAfterAnyAddBatch(StatementInformation statementInformation, long timeElapsedNanos, SQLException e) {
    logElapsed(statementInformation, timeElapsedNanos, Category.BATCH, e);
  }
```

**Comment by typekpb** [comment]
well, you seem to be not the first one to face this behaviour:

* https://github.com/p6spy/p6spy/issues/392
* https://github.com/p6spy/p6spy/issues/368

However following might be the reason we kept it the way it is: https://github.com/p6spy/p6spy/issues/368#issuecomment-280005993
If you feel there is a need to discuss again, feel free to reopen and raise your objections.
