### ISSUE TITLE
all execution times are 0

### ISSUE THREAD

**Issue by mwallach** [p6spy/p6spy#431]
Using 3.4/3.6. see statements logged but al execution times showing as 0.

**Comment by typekpb** [comment]
Any chance for providing some reproducible test case for us (maybe in the
form of junit test)?

**Comment by mwallach** [comment]
sorry for not replying. I dug into code, built with some other logging and figured out issue was my threshold was higher than my time it took for my calls. thanks for responding

**Comment by typekpb** [comment]
@mwallach excellent, thanks for responding
