### ISSUE TITLE
Get connection string from ConnectionInformation

### ISSUE THREAD

**Issue by mikhailmineev** [p6spy/p6spy#439]
If a connection to database fails, I need to log exceptions including database name. The only way I see, is to get it from connection string. So I had to fork your project to add this feature:
https://github.com/mikhailmineev/p6spy/tree/feature/conurl
If you like it, I can create a PR.

**Comment by typekpb** [comment]
would not this one do the job for you? 
> Connection has the getMetaData() to return DatabaseMetaData . DatabaseMetaData has the getURL() to return the URL for this DBMS.

(source: https://stackoverflow.com/a/5718991/1581069)

**Comment by typekpb** [comment]
feel free to close this one once clarified

**Comment by mikhailmineev** [comment]
The problem is when a connection fails, for example, connect timed out, connection object is not created

```java
    final ConnectionInformation connectionInformation = ConnectionInformation.fromDriver(passThru);
    jdbcEventListener.onBeforeGetConnection(connectionInformation);
    try {
      conn =  passThru.connect(extractRealUrl(url), properties);
      connectionInformation.setConnection(conn);
      connectionInformation.setTimeToGetConnectionNs(System.nanoTime() - start);
      jdbcEventListener.onAfterGetConnection(connectionInformation, null);
    } catch (SQLException e) {
      connectionInformation.setTimeToGetConnectionNs(System.nanoTime() - start);
      jdbcEventListener.onAfterGetConnection(connectionInformation, e);
      throw e;
    }
```
this fragment `passThru.connect(extractRealUrl(url), properties);` throws an exception

Using Microsoft JDBC Driver
