### ISSUE TITLE
allow passing spy.properties file location as a property through JDBC connection url

### ISSUE THREAD

**Issue by sadaaithal** [p6spy/p6spy#441]
Example URL:
jdbc:p6spy:oracle://ora:1521;ServiceName=ORACLE;**p6spyconfig=/tmp/myspy.props**

This would greatly help use cases where there's one big application using more than one JDBC connections. 
That way each JDBC connection can have their own spy properties file.

**Comment by typekpb** [comment]
I believe it's not doable easily currently. There might be some static
parts that would prevent that.
Any chance for providing the PR?

**Comment by typekpb** [comment]
sounds like we have no volunteer here => closing

**Comment by sadaaithal** [comment]
apologies for not following up on this.
about your earlier query, what is a "PR" ?

**Comment by typekpb** [comment]
@sadaaithal no problem 
PR = pull request

**Comment by sadaaithal** [comment]
ok so, i raise a new PR and give that to you and you would look at this issue - is that how it goes ( github newbie here, apologies )

**Comment by typekpb** [comment]
@sadaaithal well, not really. What I basically asked for is if you can provide the implementation, we could review it afterwards.

For the PR docs: https://help.github.com/articles/about-pull-requests/
