### ISSUE TITLE
How to exclude health check queries?

### ISSUE THREAD

**Issue by dialogbox** [p6spy/p6spy#442]
I'm struggling on filtering out health check queries like `SELECT 1` and `SELECT 1 FROM DUAL`.
Since we have service queries like `SELECT 1 FROM DUAL WHERE ...` and we have different DBMS, I want to filter out only exact matches of `SELECT 1` or `SELECT 1 FROM DUAL`.

However, regular expression to match these like `^(SELECT 1( FROM DUAL)?)$` is very easy but I can not find the way to write opposite filter - reject if the whole line matches.

Is there any solution for this?

Thanks!

**Comment by gavlyukovskiy** [comment]
Have you tried  negative look-around - `^(?!(SELECT 1( FROM DUAL)?)).*$`?

**Comment by dialogbox** [comment]
If it use `java.util.regex.Pattern`, yes, I have. 

My test cases was this.

```java
Pattern p = Pattern.compile("^(?!(SELECT 1( FROM DUAL)?)).*$");

assert (!p.matcher("SELECT 1").matches());
assert (!p.matcher("SELECT 1 FROM DUAL").matches());
assert (p.matcher("A SELECT 1 FROM DUAL").matches());
assert (p.matcher("SELECT 1 FROM DUAL WHERE AAA = 1").matches()); // failed
assert (p.matcher("SELECT 21 FROM DUAL WHERE AAA = 1").matches());
```

**Comment by dialogbox** [comment]
@gavlyukovskiy Great! It works. Thank you!
