### ISSUE TITLE
Documentation: Missing WildFly module.xml example

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [p6spy/p6spy#443]
Documentation: Missing WildFly module.xml example

**Comment by erickdeoliveiraleal** [comment]
also how to populate spy.properties file?

**Comment by typekpb** [comment]
would the following one be sufficient for you? https://github.com/p6spy/p6spy-it/blob/master/src/test/container/wildfly81x/modules/system/layers/base/com/p6spy/main/module.xml If so, would you mind raising a pull request to fix the currently available documentation (should be probably affecting: https://github.com/p6spy/p6spy/blob/master/docs/install.md)?

**Comment by typekpb** [comment]
the sample `module.xml` referred seem to be already part of the docs (https://p6spy.readthedocs.io/en/latest/install.html#jboss-7-1-x-wildfly-8-x-wildfly-10-x) => closing

**Comment by erickdeoliveiraleal** [comment]
The file install.md contains refers module.xml, but when viewing the file at: https://p6spy.readthedocs.io/en/latest/install.html#jboss-7-1-x-wildfly-8-x-wildfly-10-x it only shows 1 line of the module.xml
