### ISSUE TITLE
Keep bind variables names and their values

### ISSUE THREAD

**Issue by jan2ary** [p6spy/p6spy#444]
Could you please add the query log format to keep the bind variable naming and log their values, for example:
select * from city where city_name = :v_city_name and population > :v_population|{v_city_name='London', v_population=2000}

**Comment by typekpb** [comment]
@jan2ary  Any chance for providing PR for this?

**Comment by gavlyukovskiy** [comment]
Unfortunately variable name is hibernate/spring-jdbc/other library concept, so when it comes to jdbc, where p6spy operates, this information is lost and there is no way to retrieve it. 
In other words when you write 
`select * from city where city_name = :v_city_name and population > :v_population` 
hibernate/spring-jdbc/other library transforms it to `select * from city where city_name = ? and population > ?` and remembers parameter indexes, then p6spy/jdbc receives that sql and two parameters with indexes 1 and 2.

**Comment by typekpb** [comment]
@gavlyukovskiy thanks a lot for feedback
closing as it can't/won't be implemented
