### ISSUE TITLE
PreparedStatement.setTimestamp and PreparedStatement.setDate use same formatter

### ISSUE THREAD

**Issue by jonyschak** [p6spy/p6spy#445]
The Value class simply checks if the object is instanceof java.util.Date to decide if it should use the date format when converting to a string, but that means that both java.sql.Timestamp and java.sql.Date would get formatted the same way.  Would it be possible to split the instanceof check to check java.sql.Date and java.sql.Timestamp and have separate configuration properties for each?

**Comment by typekpb** [comment]
for the `java.util.Date` we have `databaseDialectDateFormat` property, we could theoretically introduce: `databaseDialectTimestampFormat` property for the `java.sql.Timestamp`.

@quintonm @felixbarny objections?

@jonyschak any chance for providing PR from your side?

**Comment by felixbarny** [comment]
no objections

**Comment by jonyschak** [comment]
I'll get the PR done soon.  For the default format, I am planning on using "dd-MMM-yy hh:mm:ss a" as that works for Oracle and SQLServer, which are the DBs that I use day to day.  Would you prefer something else?

**Comment by typekpb** [comment]
PR has been already raised. See:https://github.com/p6spy/p6spy/pull/449 .
Still need to deal with some failing tests. However the format was
following suggestion from other issue:
https://github.com/p6spy/p6spy/issues/434 so: yyyy-MM-dd'T'HH:mm:ss.SSSZ
would that one work for you as the default? As to me it makes sense to have
same defaults for both.

**Comment by jonyschak** [comment]
That works for me, I can set the value I need.  Just frustrating that DBs don't support a common format, but guess that is true about most database specific things  Thanks!
