### ISSUE TITLE
Property name does not match the one from documentation

### ISSUE THREAD

**Issue by genzak** [p6spy/p6spy#458]
Recently as a part of the issue https://github.com/p6spy/p6spy/issues/445 fix "property databaseDialectTimestampFormat for java.sql.Timestamp logging format customizations" was introduced. 

According to [the documentation](https://p6spy.readthedocs.io/en/latest/configandusage.html#common-property-file-settings) the property name should be `databaseDialectTimestampFormat`, but in the code the property name is `databaseDialectTimezoneFormat`. It's stored in the constant `com.p6spy.engine.spy.P6SpyOptions#DATABASE_DIALECT_TIMEZONE_FORMAT` and is used in methods 
```
@Override
public void setDatabaseDialectTimestampFormat(String databaseDialectTimestampFormat) {
  optionsRepository.set(String.class, DATABASE_DIALECT_TIMEZONE_FORMAT, databaseDialectTimestampFormat);
}
```
and 
```
@Override
public void setDatabaseDialectTimestampFormat(String databaseDialectTimestampFormat) {
  optionsRepository.set(String.class, DATABASE_DIALECT_TIMEZONE_FORMAT, databaseDialectTimestampFormat);
}
```
Therefore either documentation or property name should be changed to make it work as expected.

**Comment by typekpb** [comment]
fixed via https://github.com/p6spy/p6spy/commit/71190ce85901d0c0cbbcd097a1d28a433b73daf7

**Comment by typekpb** [comment]
new version should be released soon, give me a day or two

**Comment by genzak** [comment]
@typekpb thank you for providing the quick fix
