### ISSUE TITLE
cannot monitor the begin of transaction

### ISSUE THREAD

**Issue by auntyellow** [p6spy/p6spy#471]
I want to monitor the begin of transaction, but no `onBefore/AfterSetAutoCommit` method in `JdbcEventListener`. `ConnectionWrapper.setAutoCommit` just simply delegated.

**Comment by gavlyukovskiy** [comment]
In most cases getting connection from the pool is the start of transaction, if there is several transactions in the same connection you case use commits/rollbacks callbacks in the listener.

**Comment by auntyellow** [comment]
In fact, I want to calculate the time of each transaction. So I must log a time on `setAutoCommit` and on `commit`/`rollback`.

**Comment by auntyellow** [comment]
I see. Thank you for the help.

btw, AFAIK, `autoCommit` will automatically set to true after `commit()` or `rollback()`. So we must use `setAutoCommit(false)` again at the beginning of the second transaction.
