### ISSUE TITLE
Please add Automatic-Module-Name

### ISSUE THREAD

**Issue by cowwoc** [p6spy/p6spy#479]
Please add a `Automatic-Module-Name` to the manifest file. Otherwise, users of your library get the following build warning:

************************************************************************************************************************************************************************************************
* Required filename-based automodules detected: [p6spy-3.8.3.jar]. Please don't publish this project to a public artifact repository! *
************************************************************************************************************************************************************************************************

**Comment by typekpb** [comment]
will do, thanks for the suggestion!
