### ISSUE TITLE
Why do I print after setting warn

### ISSUE THREAD

**Issue by strivezsh** [p6spy/p6spy#486]
`<logger name="org.quartz" level="warn" />`
2019-08-30 17:57:51.538 INFO  [QuartzSchedulerThread] p6spy.logSQL(60) select 1 from dual
2019-08-30 17:57:51.578 INFO  [QuartzSchedulerThread] p6spy.logSQL(60) SELECT TRIGGER_NAME, TRIGGER_GROUP, NEXT_FIRE_TIME, PRIORITY FROM QRTZ_TRIGGERS WHERE SCHED_NAME = 'abc' AND TRIGGER_STATE = 'WAITING' AND NEXT_FIRE_TIME <= 1567159101497 AND (MISFIRE_INSTR = -1 OR (MISFIRE_INSTR != -1 AND NEXT_FIRE_TIME >= 1567159011538)) ORDER BY NEXT_FIRE_TIME ASC, PRIORITY DESC

**Comment by typekpb** [comment]
Depends on your p6spy configuration as well sa the logging framework config.
Can you provide sample code reproducing issue you're facing?

**Comment by strivezsh** [comment]
logback.xml
`<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <property name="pattern" value="%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) %boldYellow([%t]) %boldGreen(%logger{40}.%M\\(%L\\)) %msg%n"/>

    <appender name="console" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>${pattern}</pattern>
        </encoder>
    </appender>

    <logger name="org.quartz" level="warn"/>
    <logger name="p6spy" level="info" />

    <root level="warn">
        <appender-ref ref="console"/>
    </root>
</configuration>`

spy.properties
`
appender=com.p6spy.engine.spy.appender.Slf4JLogger
logMessageFormat=com.p6spy.engine.spy.appender.CustomLineFormat
customLogMessageFormat=%(sql)
`

with spring boot

**Comment by gavlyukovskiy** [comment]
@strivezsh you have set level warn to `org.quartz`, but those settings will not affect p6spy logger, even if quartz thread runs the SQL. P6spy doesn't have knowledge of classes that are performing SQL requests, only the fact that those SQL were executed.

**Comment by mathisdt** [comment]
I think
`<logger name="p6spy" level="warn" />`
should do what you want.

**Comment by gavlyukovskiy** [comment]
@mathisdt it will actually block nearly all of the p6spy logs, not only ones that come from quartz.

**Comment by mathisdt** [comment]
As far as I understood the @strivezsh that was what he wanted - to not print the SQL statements anymore. If the user's intention was to generally print SQL statements but not those originating from Quartz, then of course my answer is false.

**Comment by strivezsh** [comment]
i want print other sql
not print quartz QuartzSchedulerThread sql

**Comment by strivezsh** [comment]
log4j.properties
`
log4j.rootLogger=info, stdout
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%n%-d{yyyy-MM-dd HH:mm:ss}%n[%p]-[Thread: %t]-[%C.%M()]: %m%n

log4j.logger.com.company=warn
`

java code
`
package com.company;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class Main {

    public static void main(String[] args) throws Exception {
        Test t = new Test();
        t.show();
    }

    static class Test {
        private static final Logger G = LoggerFactory.getLogger(Test.class);

        public void show() throws Exception {
            G.info("start");
            query();
            G.info("end");
        }

        public void query() throws SQLException {
            Connection cn = CnUtils.getCn();
            PreparedStatement st = cn.prepareStatement("select 1 from dual");
            ResultSet rs = st.executeQuery();
            rs.next();
            G.info("result set: " + rs.getObject(1));
            rs.close();
            st.close();
            cn.close();
        }
    }

}
`
spy.properties
`
modulelist=com.p6spy.engine.spy.P6SpyFactory,com.p6spy.engine.logging.P6LogFactory,com.p6spy.engine.outage.P6OutageFactory
appender=com.p6spy.engine.spy.appender.Slf4JLogger
other default
`

why print
[INFO]-[Thread: main]-[com.p6spy.engine.spy.appender.Slf4JLogger.logSQL()]: 1582035442646|21|statement|connection 0|url jdbc:p6spy:oracle:thin:@localhost:1521:orcl|select 1 from dual|select 1 from dual

**Comment by gavlyukovskiy** [comment]
@strivezsh when you're setting `log4j.logger.com.company=warn` it affects only loggers with name `com.company.*` and since your logger `G` was defined in that package the info messages are not printed. But logger that P6Spy uses is not defined in your package - https://github.com/p6spy/p6spy/blob/master/src/main/java/com/p6spy/engine/spy/appender/Slf4JLogger.java#L34 and has name `p6spy`. 

If you want only warnings to be printed from P6Spy then the correct configuration would be `log4j.logger.p6spy=warn`, but it has no relation to threads or quartz, meaning that this setting will disable logging from the whole application. 
I assume that you want to log queries coming from one package and not log queries from another package, right? Because P6Spy operates on level of `DataSource` or `Driver` it doesn't know the package, that was running the query and there is no way to figure that out.

**Comment by gavlyukovskiy** [comment]
@strivezsh I hope you got the answer for your question. please let me know if you need anything else.
