### ISSUE TITLE
can't return any result when use P6SpyDriver 

### ISSUE THREAD

**Issue by curdlx** [p6spy/p6spy#490]
version 3.8.6
when I change "com.mysql.jdbc.Driver" to "com.p6spy.engine.spy.P6SpyDriver" , when the table field is a mysql reserved words like "name", I can't get any result,the sql output is:
select * from t_user where `name` like  concat('%', 'shawn', '%')

**Comment by typekpb** [comment]
Can you provide us some example project? The best would be to demonstrate it via p6spy junit test, that would be failing.

**Comment by curdlx** [comment]
not a issue
