### ISSUE TITLE
Database dialect dependent binary data representation

### ISSUE THREAD

**Issue by kekbur** [p6spy/p6spy#501]
Currently p6spy logs binary parameter values as [hex encoded strings](https://github.com/p6spy/p6spy/blob/c4392d22a76f6851997e4857d1ffb30d96574c7b/src/main/java/com/p6spy/engine/common/Value.java#L104). However, different database engines expect different formats for binary input which means that the logged queries cannot be copied and pasted and then executed without modification.

I propose adding a new configuration option similar to `logMessageFormat` which would allow customizing the representation of binary data. For example:

`binaryDataFormat=com.p6spy.engine.spy.appender.PostgreSQLBinaryFormat`

Currently:

```sql
where refreshtok0_.token='8088BAD639F'
```

With proposed PostgreSQLBinaryFormat:

```sql
where refreshtok0_.token='\x8088BAD639F'
```

With proposed MySQLBinaryFormat:

```sql
where refreshtok0_.token=0x8088BAD639F
```

Would you accept a pull request implementing this feature as described here?

**Comment by gavlyukovskiy** [comment]
@kekbur I think it would be good feature to have, ping me in PR and I will review it

**Comment by kekbur** [comment]
@gavlyukovskiy Thanks a bunch.
