### ISSUE TITLE
Question: Does p6spy work with Tomcat 9.X?

### ISSUE THREAD

**Issue by irishgordo** [p6spy/p6spy#508]
I saw here:
https://p6spy.readthedocs.io/en/latest/install.html#apache-tomcat-and-apache-tomee

That it's listed to work with:
Apache Tomcat 6.x, 7.x, 8.x and TomEE 1.6.x

And was wondering if there's any plan for p6spy to work with Tomcat 9.X?  

Thanks for any help/info!

**Comment by typekpb** [comment]
docs fixed, Tomcat 9 is supported, see: https://p6spy.readthedocs.io/en/latest/install.html#apache-tomcat-and-apache-tomee
