### ISSUE TITLE
log blank sql when category is commit?

### ISSUE THREAD

**Issue by test210820** [p6spy/p6spy#522]
![image](https://user-images.githubusercontent.com/65008815/108598498-e48c8580-73c8-11eb-9a59-18a84aa2d97c.png)

## spy.properties
```
appender=com.p6spy.engine.spy.appender.Slf4JLogger

logMessageFormat=com.p6spy.engine.spy.appender.CustomLineFormat

customLogMessageFormat=currentTime:%(currentTime)|executionTime:%(executionTime)|category:%(category)|connection:%(connectionId)\n==>%(sql)\n
```

**Comment by typekpb** [comment]
@zxf-thingsmatrix what would you expect in such a case? No message in the log at all?
I have currently very limited capacity for this project, would the soltion provided in: https://github.com/p6spy/p6spy/pull/521 by any chance work for you?
