### ISSUE TITLE
P6SpyOutageThread is not a daemon thread

### ISSUE THREAD

**Issue by nimatrueway** [p6spy/p6spy#523]
com/p6spy/engine/outage/P6OutageDetector.java:64
```
    	ThreadGroup group = new ThreadGroup("P6SpyThreadGroup");
        group.setDaemon(true);
        Thread outageThread = new Thread(group, this, "P6SpyOutageThread");
        outageThread.start();
```

Apparently setting daemon on thread-group doesn't propagate the daemon-value to the thread members.

![image](https://user-images.githubusercontent.com/2261274/109689997-ba5e6480-7b3a-11eb-9a0a-334364c727f9.png)

AdoptOpenJdk 8.x

**Comment by typekpb** [comment]
closing as the referred PR has been merged
