### ISSUE TITLE
Add new appender NoLogger.java for production use

### ISSUE THREAD

**Issue by Quindlen** [p6spy/p6spy#535]
Would be nice to be able to keep this and run it in production (without logging) to use p6spy as a jdbc full wrapper driver. I'd like to keep p6spy configured in production for the wrapper, but not have logging on. 

Please Add new appender NoLogger,java for production use.

com.p6spy.engine.spy.appender.NoLogger.
There may be a better way, but I came up with this one.

public class NoLogger extends FormattedLogger {

  protected PrintStream getStream() {
    return System.out;
  }

  @Override
  public void logException(Exception e) {
    e.printStackTrace(getStream());
  }

  @Override
  public void logText(String text) {
  }

  @Override
  public boolean isCategoryEnabled(Category category) {
    // no restrictions on logger side
    return true;
  }
}

Thank you.

**Comment by gavlyukovskiy** [comment]
I think far easier way would be to not register `com.p6spy.engine.logging.P6LogFactory` module if you don't need logging. It can be done using `modulelist` property which defaults to:
```
modulelist=com.p6spy.engine.spy.P6SpyFactory,com.p6spy.engine.logging.P6LogFactory
```
you need to keep `P6SpyFactory` because it's internal module. 

You can also update it during runtime, see [example](https://github.com/gavlyukovskiy/spring-boot-data-source-decorator/blob/master/datasource-decorator-spring-boot-autoconfigure/src/main/java/com/github/gavlyukovskiy/boot/jdbc/decorator/p6spy/P6SpyConfiguration.java#L84).

Feel free to reopen if you have any questions.

**Comment by Quindlen** [comment]
Thank you for getting back to us. We use p6spy for one main reason. We
needed to cast from datetime 2 to datetime. So we do the cast and created a
nologger to not log.


It's a good solution for us until we convert the fields in the database so
casting would not be needed.

Thanks

Pete

**Comment by gavlyukovskiy** [comment]
I'm not sure what cast do you mean specifically? If you remove logging module p6spy will function as usual, with only difference that it will not register logging listener, so there is no need to provide `NoOpLogger` implementation

**Comment by Quindlen** [comment]
Thanks. We will give the no log option a try.

We are trying to migrate over to a new sql server. On a datetime field, we ran into an instance where jdbc changed the timestamp field to a datetime2. So we took a p6spy class and modified it that when it finds the datetime2 meta, to add a cast to the query to datetime. The issue is at this time we cannot change the database. So we used p6spy engine to make the cast before it hits the server. I did not see another tool to use. So we currently using p6spy for it.

Pete

On February 21, 2022 9:46:14 AM PST, Arthur Gavlyukovskiy ***@***.***> wrote:
>I'm not sure what cast do you mean specifically? If you remove logging module p6spy will function as usual, with only difference that it will not register logging listener, so there is no need to provide `NoOpLogger` implementation
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/p6spy/p6spy/issues/535#issuecomment-1047111627
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
Peter Stark 
Olympia, WA 
203-241-5894 
***@***.***
http://www.linkedin.com/in/peter-stark-it

**Comment by Quindlen** [comment]
I'll ask my boss tomorrow to see if I can share our p6spy modifications to the project to see if maybe you can add a, feature in for us, so we don't have a forked version.
Pete 

On February 21, 2022 11:20:38 AM PST, Peter Stark ***@***.***> wrote:
>Thanks. We will give the no log option a try.
>
>We are trying to migrate over to a new sql server. On a datetime field, we ran into an instance where jdbc changed the timestamp field to a datetime2. So we took a p6spy class and modified it that when it finds the datetime2 meta, to add a cast to the query to datetime. The issue is at this time we cannot change the database. So we used p6spy engine to make the cast before it hits the server. I did not see another tool to use. So we currently using p6spy for it.
>
>Pete
>
>On February 21, 2022 9:46:14 AM PST, Arthur Gavlyukovskiy ***@***.***> wrote:
>>I'm not sure what cast do you mean specifically? If you remove logging module p6spy will function as usual, with only difference that it will not register logging listener, so there is no need to provide `NoOpLogger` implementation
>>
>>-- 
>>Reply to this email directly or view it on GitHub:
>>https://github.com/p6spy/p6spy/issues/535#issuecomment-1047111627
>>You are receiving this because you authored the thread.
>>
>>Message ID: ***@***.***>
>Peter Stark 
>Olympia, WA 
>203-241-5894 
***@***.***
>http://www.linkedin.com/in/peter-stark-it 

Peter Stark 
Olympia, WA 
203-241-5894 
***@***.***
http://www.linkedin.com/in/peter-stark-it

**Comment by gavlyukovskiy** [comment]
@Quindlen I assume you're talking about your other issue https://github.com/p6spy/p6spy/issues/534 here, if so let's move discussion there.

**Comment by Quindlen** [comment]
Thank you. We will upgrade to a later version once 534 and 535 are complete. Thank you for working on 535!
