### ISSUE TITLE
Does the newer version support use with SQL Profiler or IronTrack SQL?

### ISSUE THREAD

**Issue by zhanghb1994** [p6spy/p6spy#544]
Today I read a blog about p6spy and learned about SQL Profiler and IronTrack SQL. However, the version of p6spy on the blog is quite old, so I would like to know if the newer version supports use with SQL Profiler or IronTrack SQL.

**Comment by gavlyukovskiy** [comment]
@zhanghb1994 hard to say as I couldn't find source code for any of those. Have you tried running those with never versions of p6spy?

**Comment by zhanghb1994** [comment]
When I have time, I wanna go to try running with never versions and see what happens.

**Comment by gavlyukovskiy** [comment]
@zhanghb1994 go ahead. Please open issues only in case something is not working, by default we try to make versions of p6spy backward compatible, but we do not test latest versions of projects built on top of p6spy to verify it's compatibility, such requests better be routed to maintainers of such projects.

Feel free to reopen this issue if you find anything, we'll try to help
