### ISSUE TITLE
Does p6spy support  method-name printing while printing the SQL statement in Spring Boot application ?

### ISSUE THREAD

**Issue by Dwvil** [p6spy/p6spy#545]
As the title says,  does p6spy support  method-name printing in current version(or in the future) ? Maybe I overlooked the configuration I wanted in the configuration document ?

**Comment by gavlyukovskiy** [comment]
Hi @Dwvil, do you mean spring-data repository name or something else?

**Comment by Dwvil** [comment]
> Hi @Dwvil, do you mean spring-data repository name or something else?
Thanks for your replay ! Now I want to describe my issue with an example below here:
There is a simple method with a mybatis annotation @Select

**Comment by Dwvil** [comment]
> Hi @Dwvil, do you mean spring-data repository name or something else?

Thanks for ur replay ! I would like to describe my issue with an example below:

There is a simple method with a mybatis annotation `@Select`
![image](https://user-images.githubusercontent.com/33611796/155249378-684ce18f-d2a6-47ef-aeac-40dab7173b88.png)
P6spy prints the information(_Consume Time&Execute SQL_) below to the console after I ran the method `listFatoryIds()`
![image](https://user-images.githubusercontent.com/33611796/155249455-cfd4eb06-dc76-4e94-9527-701926ecafe7.png)
It's good, but I want to print the method name to the console, like `com.xxx.xxx.page.DemoClass#listFatoryIds`.

Does P6spy meet my requirement now? 

Thank u very much!

**Comment by gavlyukovskiy** [comment]
@Dwvil this does not look like p6spy output, in any case p6spy is not able to get information of method that has produced SQL query. Perhaps you can check [Mybatis Logging](https://mybatis.org/mybatis-3/logging.html) page instead.
