### ISSUE TITLE
P6psy stopped working after upgrading to spring boot from 2.5.5 to 2.7.7

### ISSUE THREAD

**Issue by prashanthdesu** [p6spy/p6spy#553]
Hi,

I have configured p6spy using the datasource way like "P6DataSource(new HikariDataSource(hikariConfig))" and had an empty spy.properties file to use default values. I was able to see the p6spy logs. I upgraded the spring boot version from 2.5.5 to 2.7.7. After the upgrade, I can't see any logs. is there any compatibility issue between spring-boot(2.7.7) and p6spy

**Comment by prashanthdesu** [comment]
During this upgrade, I have to move from spring-cloud-sleuth-core to spring-cloud-sleuth-instrumentation for compatibility with spring-boot(2.7.7). Does any think this might be the issue.

**Comment by prashanthdesu** [comment]
@gavlyukovskiy Can you help me with this.

**Comment by gavlyukovskiy** [comment]
If you provide a small, reproducible example, then I can try to help. Without that, it's hard to say what's wrong. I know that integration with p6spy was added to spring-cloud-sleuth, so it might conflict with manual wrapping.

**Comment by prashanthdesu** [comment]
I am not sure how to reproduce this error. How can we check if it is a conflict with manual wrapping

**Comment by gavlyukovskiy** [comment]
You can try injecting DataSource and checking in the debugger if it has one or multiple layers of P6DataSource. Also one other option is to enable spring boot debug logs and check if any autoconfiguration related to p6spy has been applied or not

**Comment by prashanthdesu** [comment]
I enabled the spring debug logs and saw that p6spy connection wrapper has been set


Setting JDBC Connection **[com.p6spy.engine.wrapper.ConnectionWrapper@65bb3159]** read-only

[o.s.orm.jpa.JpaTransactionManager,http-nio-127.0.0.1-7100-exec-2] Exposing JPA transaction as JDBC 

[org.springframework.orm.jpa.vendor.HibernateJpaDialect$HibernateConnectionHandle@1f8185a7]
[o.s.cloud.sleuth.SpanAndScope,http-nio-127.0.0.1-7100-exec-2] Closing span 

[NoopSpan(a18e70ef204a16cf/94c08ff987c3b905)], scope is not null [false]
[o.s.cloud.sleuth.SpanAndScope,http-nio-127.0.0.1-7100-exec-2] Closing span 

[NoopSpan(a18e70ef204a16cf/096a4fd86183b79d)], scope is not null [true]
 [o.s.cloud.sleuth.SpanAndScope,http-nio-127.0.0.1-7100-exec-2] Closing span 

[NoopSpan(a18e70ef204a16cf/c5c85ec5f75104d7)], scope is not null [false]

[o.s.cloud.sleuth.SpanAndScope,http-nio-127.0.0.1-7100-exec-2] Closing span [NoopSpan(a18e70ef204a16cf/69bfe1f024f3dc10)], scope is not null [true]

 [o.s.cloud.sleuth.SpanAndScope,http-nio-127.0.0.1-7100-exec-2] Closing span [NoopSpan(a18e70ef204a16cf/c5c85ec5f75104d7)], scope is not null [false]

[o.s.cloud.sleuth.SpanAndScope,http-nio-127.0.0.1-7100-exec-2] Closing span [NoopSpan(a18e70ef204a16cf/69bfe1f024f3dc10)], scope is not null [true]

[o.s.orm.jpa.JpaTransactionManager,http-nio-127.0.0.1-7100-exec-2] Initiating transaction commit
 [o.s.orm.jpa.JpaTransactionManager,http-nio-127.0.0.1-7100-exec-2] Committing JPA transaction on EntityManager [SessionImpl(791993345<open>)]

[o.s.jdbc.datasource.DataSourceUtils,http-nio-127.0.0.1-7100-exec-2] **Resetting read-only flag of JDBC Connection [com.p6spy.engine.wrapper.ConnectionWrapper@65bb3159]**

[o.s.orm.jpa.JpaTransactionManager,http-nio-127.0.0.1-7100-exec-2] Not closing pre-bound JPA EntityManager after transaction

**Comment by prashanthdesu** [comment]
I have come across this [doc](https://docs.spring.io/spring-cloud-sleuth/docs/current-SNAPSHOT/reference/html/appendix.html#appendix), Here there is a property "spring.sleuth.jdbc.p6spy.enable-logging=true",@gavlyukovskiy is this new way of enabling p6spy

**Comment by gavlyukovskiy** [comment]
Well, if you're using spring-cloud-sleuth. In this case, you shouldn't wrap your datasource in P6DataSource, because Sleuth does that by default when finds p6spy in classpath.
Regarding property - whether logging is enabled or not, the p6spy itself is always "enabled", but by default it's only used for traces, not logging.

**Comment by prashanthdesu** [comment]
Earlier I used spring-cloud-sleuth-core and wrapped the datasource and was able to see the logs. I replaced spring-cloud-sleuth-core with spring-cloud-sleuth-instrumentation and started seeing this error. Doesn't spring-cloud-sleuth-core wrap the data source by default

**Comment by prashanthdesu** [comment]
I also added a path for log file in spy.properties and it got picked up earlier but with instrumentation dependency, spy.properties in ineffective. I can set the log path only using the property "spring.sleuth.jdbc.p6spy.log-file".

**Comment by gavlyukovskiy** [comment]
> Doesn't spring-cloud-sleuth-core wrap the data source by default

It does, that's why you shouldn't wrap data source twice. And since sleuth configures it in certain way to apply tracing, some properties from `spy.properties` are overridden. If I recall my code correctly, most of the properties will work, but some are simply incompatible. 
As general rule if there is a property available from `spring.sleuth.jdbc.p6spy.*`, then use that, if noy - you can probably still configure it through `spy.properties`
